### ISSUE TITLE
Clarification of Lab 1 - kojo, task 7

### ISSUE THREAD

**Issue by annasjovall** [lunduniversity/introprog#132]
In lab 1, kojo, the following task is described as:

_"Uppgift 7. Tidmätning. Hur snabb är din dator?
a) Skriv in koden nedan i Kojos editor och kör upprepade gånger med den
gröna play-knappen. Hur lång tid tar det för din dator att räkna till 4.4 miljar-
der?"_

What is the task itself? Should you press the green button 44 times to reach 4,4 billion or should the code be changed so that only one run will suffice?

**Comment by bjornregnell** [comment]
Nice catch! I'll look into it soon.

**Comment by bjornregnell** [comment]
One run it was supposed to be. I'll try to rephrase it so it becomes clearer.

**Comment by bjornregnell** [comment]
Now rephrased the task and split it into two substasks. Better like this?
https://github.com/lunduniversity/introprog/commit/92a4281fc8

**Comment by annasjovall** [comment]
Yes! Much clearer!
