### ISSUE TITLE
Clarification of Lab 3 - pirates, task 2

### ISSUE THREAD

**Issue by annasjovall** [lunduniversity/introprog#135]
_2 b) Ändra i main för att testa att din besättning läses in från filen och skrivs
ut dem i konsolen. Stämmer det med filinnehållet?_

Is this meant as "skrivs ut i konsolen" or "skriver ut dem i konsolen"? The formulation needs clarification as the task could mean either that println should be in readCrew or added in main as a test.

**Comment by majstenmark** [comment]
I did clarify it ... BUT I don't think you have an updated version because it was changed from that formulation (and a few more in to come in the appendix). Recompile the pdf from latex to get the latest version.
