### ISSUE TITLE
Which commit was sent to the press?

### ISSUE THREAD

**Issue by ErikBjare** [lunduniversity/introprog#178]
I'd like to create a release here on GitHub to mark the occasion :smile:

**Comment by ErikBjare** [comment]
I have prepared a draft: https://github.com/lunduniversity/introprog/releases/tag/untagged-f71850665114d3569afd

I'll go ahead and upload a PDF as soon as I get confirmation about which commit was the last one.

**Comment by bjornregnell** [comment]
This is THE commit sent to print:
https://github.com/lunduniversity/introprog/commit/bf150e5b4de4bec9e9d5bddfaa1a64ffc1b5cc5e
Can you connect the specific current versions of the pdf:s
solutions.pdf compendium.pdf, exercise.pdf
to the release so we have a refernce for the errata etc?
/B

**Comment by bjornregnell** [comment]
sorry: THIS is *THE* commit :)
https://github.com/lunduniversity/introprog/commit/d5b7229cdee0b015c43cf5f4e6ea5d4fd9a4179f
Is it possible to connect the specific current versions of these pdf:s :
solutions.pdf, compendium.pdf, exercise.pdf
to the release so we have a reference for the errata etc?
/B

From: Björn Regnell
Sent: den 29 augusti 2016 15:42
To: 'Erik Bjäreholt' <erik@bjareho.lt>
Cc: 'lunduniversity/introprog' <reply@reply.github.com>
Subject: RE: [lunduniversity/introprog] Which commit was sent to the press? (#178)

This is THE commit sent to print:
https://github.com/lunduniversity/introprog/commit/bf150e5b4de4bec9e9d5bddfaa1a64ffc1b5cc5e
Can you connect the specific current versions of the pdf:s
solutions.pdf compendium.pdf, exercise.pdf
to the release so we have a refernce for the errata etc?
/B

**Comment by ErikBjare** [comment]
I will attach the PDFs to the release!

I figured that's the one you meant, publishing the release now!
