### ISSUE TITLE
Folder structure of `compendium/modules`

### ISSUE THREAD

**Issue by ErikBjare** [lunduniversity/introprog#18]
In my opinion, it's currently a mess to navigate. You need to find the list of topic -> week mappings to be able to find a particular module you are looking for.

I propose changing from the following format:

```
modules
├── w01-chapter.tex
├── w01-exercise.tex
├── w01-lab.tex
├── w01-solutions.tex
├── w02-chapter.tex
├── w02-exercise.tex
├── w02-lab.tex
├── w02-solutions.tex
<...>
├── w14-chapter.tex
├── w14-exercise.tex
├── w14-lab.tex
└── w14-solutions.tex
```

To the following format:

```
modules
├── w01-expressions-kojo
│   ├── w01-chapter.tex
│   ├── w01-exercise.tex
│   ├── w01-lab.tex
│   └── w01-solutions.tex
├── w02-programs
│   ├── w02-chapter.tex
│   ├── w02-exercise.tex
│   ├── w02-lab.tex
│   └── w02-solutions.tex
<...>
```

The folder names would be named as such: w{weeknumber}-{exercisename}-{labname}.

However, there is one added complexity which is probably the reason for this folder structure in the first place. The `compendium.tex` file which uses `\input` to include all the files using a foreach. My proposed solution to this is to generate the `\input` lines using a simple bash-script and put the output in `./generated`. The script would look something like this:

``` bash
#!/bin/bash
for module in modules/*; do
    week=$(echo $module | egrep -o "w[0-9]+")
    for chapterfile in "chapter" "exercise" "lab"; do
        echo "\\input{$module/${week}-${chapterfile}.tex}"
    done
done
```

Not sure how well this would merge, but I guess git would play nice as long as one carefully did everything with `git mv` (as the changes I have staged in my tree right now as I prepare a PR). 

So, thoughts/critique/feedback?

**Comment by ErikBjare** [comment]
The proposal has been implemented in https://github.com/ErikBjare/introprog/commit/f7dfcff34eb8c8edb455037e50cd500b81d47a46 but I won't make a PR until all the PR's that we expect to come rolling in the coming week are in, in part due to forgetting to branch before my own WIP on the life-lab (w12).

**Comment by ErikBjare** [comment]
I should add that this folder structure has one additional significant advantage, images and other misc. includes can be put in the same folder as the lab in which they are included without cluttering the already large `compendium/modules` folder.

**Comment by bjornregnell** [comment]
I agree that the folder structure can be improved, and should be refactored eventually. But I suggest that we wait a bit and decide om when to refactor while stipulating a freeze of all work for a short period to minimize merge problems. I'm not sure distributing all imaged is the best, as some images will recur in many places (lecture slides, more than one exercise/lab, etc). Let's think about this a bit more.

**Comment by bjornregnell** [comment]
Another thing: I want to, if possible, implement all generated stuff base on the data structure in plan/Plan.scala as I want to change stuff in one place. When a module/exercise/lab is renamed/moved everything should be fixed automatically by running sbt gen...

**Comment by ErikBjare** [comment]
Ah, that's fair. Still, I suspect merge problems would be minimal (non-existent) as long as no one else moves any file, if this is a primary pain-point we could do a few tests to exclude the possibility of issues down the line.

However, regarding the proper directory for images I'd prefer an answer asap since I want to include a few in the lab about Life.

**Comment by bjornregnell** [comment]
Put images in img/ and if you want make a subdir in img with a name that says something about the topic of the images e.g. img/life/  if that is ok for now?

**Comment by bjornregnell** [comment]
I mean in the introprog/img/ dir at the root of this repo; introprog/img/life/your.jpg

**Comment by ErikBjare** [comment]
Ah, missed that dir. Will do!

**Comment by bjornregnell** [comment]
I haven't forgotten about this but I think it is better to wait until after the first review to see if the structure is stable. I need to decide how much should be manual and how much the automatic plan generation that should be updated - some work actually...

**Comment by bjornregnell** [comment]
Too much work. Closing this for now. At some point in the future we should make a big refactor but that has to wait until more things has settled; also considering how to generate a web-version of the compendium and an English translation etc.
