### ISSUE TITLE
Exercise var/val/def proposal

### ISSUE THREAD

**Issue by gustavcedersjo** [lunduniversity/introprog#183]
In chapter 1, exercise 15, many students missed the "gurka" printout on the definition and use of `z` and `w` respectively.

To illustrate when defs and vars evaluated, I propose that we use

```
var z = math.random
def w = math.random
```

The {}-expression could be explained separately.

**Comment by bjornregnell** [comment]
Fixed! Now task number 23 in chapter 1 in compendium1.pdf
