### ISSUE TITLE
The use of "heltal" in chapter 2

### ISSUE THREAD

**Issue by gustavcedersjo** [lunduniversity/introprog#185]
In the exercises in chapter 2, the word "heltal" used both for the positive integers (or natural numbers) as well as all integers. I think the students will understand from the context which numbers it should be, but I suggest we use "positiva heltal" or "naturliga tal" when that is what is meant.

**Comment by ErikBjare** [comment]
I think positive integers would be the preferred term here.

**Comment by bjornregnell** [comment]
Fixed by https://github.com/lunduniversity/introprog/commit/c49e29a42b2a2d1fa371f1980f69228b4debc2af
