### ISSUE TITLE
improve SWAP task in exercise programs

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#187]
step by step towards understanding temp:
var x = 42
var y = 24
val oldX = x
val oldY = y
y = x
x = oldY
// as we can see: oldX is not needed

**Comment by gustavcedersjo** [comment]
Start with the following.
```
var x = 42
var y = 24
val oldX = x
val oldY = y
y = oldX
x = oldY
```
At `y = oldX`, `x` hasen't changed, so we can write `y = x` and remove `val oldX = x`.
```
var x = 42
var y = 24
val oldY = y
y = x
x = oldY
```
The last step is to rename `oldY` to `temp`.
```
var x = 42
var y = 24
val temp = y
y = x
x = temp
```
And there you have the swap algorithm using `temp`.

**Comment by bjornregnell** [comment]
This is very clear and thorough! Maybe a bit long to comprehend all steps at one go for a beginner, but it is a nice exercise in assignment!
