### ISSUE TITLE
swedish translation of 'qualified name', lab blockmole

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#188]
'kvalificerat namn' is a suboptimal translation; can we find something else?
We also need to integrate this terminology in exercises and lectures, not just in lab blockmole

**Comment by gustavcedersjo** [comment]
What about "lokalt namn" versus "fullständigt namn"?
A possible confusion with "fullständigt namn" could be the difference between qualified name and fully qualified name, i.e. `b.x` versus `a.b.x` in the example below.
```
package a {
  package b {
    def x = 42
  }
  def y = b.x
}
```

**Comment by bjornregnell** [comment]
is there something similar to "partially qualified" in Swedish. Mabye "nästan fullständigt namn" == "almost complete name"?

**Comment by bjornregnell** [comment]
Can't find this when searching the text for "kvalificerat" so I'm closing this.
