### ISSUE TITLE
Remove PDFs from history

### ISSUE THREAD

**Issue by ErikBjare** [lunduniversity/introprog#196]
The repo is currently huge due to all the PDFs being in history.

We should fix this when this round of the course is over so it's fixed by next year. Might require a `git filter-branch` that could require a force push.

**Comment by jos-rosenqvist-3812** [comment]
The master branch has been stripped of PDFs now, making the repo a lot smaller (I've gotten it down to about 260 MB locally). However, the tex2markdown branch still contains PDF history, so there's still more space that can be saved.

**Comment by bjornregnell** [comment]
Yes, good! I have run filter-branch according to this "dangerous" git history patch:
https://github.com/lunduniversity/introprog/blob/master/util/git-utils/scrap-all-pdfs.sh
I think it makes sense to remove all other branches except master as they seem old and inactive. 
@ErikBjare @ViktorClaesson @StefanEJonsson :
Is it ok if I delete these branches?
* https://github.com/lunduniversity/introprog/tree/tex2markdown
* https://github.com/lunduniversity/introprog/tree/ViktorClaesson-master
* https://github.com/lunduniversity/introprog/tree/StefanEJonsson-patch-3

**Comment by ViktorClaesson** [comment]
Yes, at least my branch.

Mvh, Viktor

**Comment by ErikBjare** [comment]
My branch doesn't contain anything of particular value, go right ahead.

**Comment by bjornregnell** [comment]
Should be fixed now. I've gitignored *.pdf in some dirs with many big pdfs and I now need to think about how to publish them outside are reop and automate that process... 
@jos-rosenqvist-3812 Does all look ok now? Did your repo size go down after synching?

**Comment by jos-rosenqvist-3812** [comment]
Yes, it looks good. The repo size went down by 30 MiB or so, so it's not as big of an impact as when the history of master was rewritten, but it's still a nice gain.

**Comment by ErikBjare** [comment]
@bjornregnell We already have Travis building the PDFs, easy to set up an automatic upload of the build artifacts to an FTP server or similar.

**Comment by bjornregnell** [comment]
I'm not sure how to do with the credentials to allow scp from travis to our university servers, so I'll do that manually and for snapshots we can use latexonline.cc and I'm closing this for now. I have updated the README with links to release, lth mirror and latexonline snapshots.
