### ISSUE TITLE
Gather feedback from students

### ISSUE THREAD

**Issue by ErikBjare** [lunduniversity/introprog#197]
We should collect feedback from students on a detail level so that unclear instructions and redundant/premature exercises will get weeded out.

The question is how. And when should the work on the revised 2017 edition begin? We probably need to start collecting feedback now so we can make a good revision later on.

**Comment by Zolomon** [comment]
We could use [Google Tag Manager](https://www.google.com/analytics/tag-manager/) and implement a test runner that utilises that every time a student runs the test runner to verify their progress. However that should then be an opt-in feature. 

There are other ways, we could probably use GitLab or write our own server that receives the data from the potential tool.

**Comment by bjornregnell** [comment]
This is on-going work. But most things are weeded out by now.
