### ISSUE TITLE
w06-turtlegraphics, left out return type

### ISSUE THREAD

**Issue by emilwihlander** [lunduniversity/introprog#205]
In the definition for Turtle in turtlegraphics all methods have their return type explicitly defined except for the jumpTo method. Is there a reason for this or is it just a inconsistency that should be corrected?

**Comment by bjornregnell** [comment]
Good catch! In a Scala-API developed for general re-usability it is idiomatic to provide return types for a) documentation purposes and to b) avoid compiler inference surprises. The jumpTo-method should have explicit return type as well; PR welcome ;)
/B

**Comment by bjornregnell** [comment]
turtle is deprecated
