### ISSUE TITLE
Idea: Lab on `match`

### ISSUE THREAD

**Issue by gustavcedersjo** [lunduniversity/introprog#215]
Goals:
- Learn to `match` over `case class`es.
- Learn to use a `trait` as a base type.

Task:
1. Build a small expression language with one `case class` per language construct.
2. Create an evaluation function using `match`.
3. Extend the language with a new construct and update the evaluator.

Extra:
1. Build a parser for the language.
2. Create a pretty-printer that is compatible with the parser.

**Comment by bjornregnell** [comment]
Nice idea! One potential problem: wouldn't this require recursion? But I guess it's only needed for the parser, which is extra?

**Comment by gustavcedersjo** [comment]
Yes, it would require recursion.

But maybe an expression evaluator it is not a bad introduction to recursion? I don't know if anyone has done research on what kind of recursion is easier to understand for students, but I wouldn't be surprised if structural recursion is easier for most students because you can "see" the substructures.

**Comment by bjornregnell** [comment]
Yes, maybe so. From an alignment perspective we need to consider what to assess in terms of goals, but I'm very open to including recursion in a lab even if its not part of the written exam / syllabus.

**Comment by bjornregnell** [comment]
This could be a project. Or we consider recursion if there is an update to the second programming course especially tailored for CSE/ICT students

**Comment by bjornregnell** [comment]
Closing this for now as recursion is unlikely to be in scope of the first course for the next years.
