### ISSUE TITLE
w09-maze: nested function have different names in method "random"

### ISSUE THREAD

**Issue by Chokladmunk** [lunduniversity/introprog#216]
In the code overview, the functions are named "addSurroundingWalls" and "isThreeWallsAround".
In the instructions, the functions that's mentioned are called "addWallToList" and "threeWallsAround".
In the workspace, the functions are labeled "addSurroundingWalls" and "threeWallsAround".

**Comment by bjornregnell** [comment]
Good catch! 
Fixed here: https://github.com/lunduniversity/introprog/commit/b38e3ee2a12adc6a957
Thanx!

**Comment by Chokladmunk** [comment]
In the workspace the function "threeWallsAround" is still labeled "threeWallsAround".

**Comment by bjornregnell** [comment]
Ooops. Thanks! Should be fixed now in https://github.com/lunduniversity/introprog/commit/47ee247607189b20e154
