### ISSUE TITLE
w09-maze: Can't load mazes when path contains spaces

### ISSUE THREAD

**Issue by jos-rosenqvist-3812** [lunduniversity/introprog#217]
In the `maze` lab, loading the maze files will fail with a `FileNotFoundException` if the path to the files contains spaces.

`getResourcesPath` returns a string that contains `%20` instead of spaces. Doing `.replace("%20", " ")` on the string makes maze loading work correctly, but it doesn't feel like a proper solution. Maybe there are other characters that also get returned as `%` escape sequences.

**Comment by bjornregnell** [comment]
Good catch! Yes this was a quick hack and not general. If you want you could investigate these SO answers (probably getAbsolutePath() on fixes the issue?):
http://stackoverflow.com/questions/6164448/convert-url-to-normal-windows-filename-java 
and then perhaps come with a Pull Request on the relevant workspace files of this repo to fix this issue?
