### ISSUE TITLE
Search/sort task 15 b) doesn't compile

### ISSUE THREAD

**Issue by jos-rosenqvist-3812** [lunduniversity/introprog#222]
In the search/sort chapter, task 15 b) is written as if the provided `isSorted` function works correctly, but it fails compilation with `error: No implicit Ordering defined for T.`

Task 15 d) contains the exact same code, but correctly says that there is a problem with the code.

**Comment by bjornregnell** [comment]
Good catch! Should be:
def isSorted[T:Ordering](xs: Seq[T]):Boolean = xs == xs.sorted
