### ISSUE TITLE
bank examples use IDs that don't fit in the specified data type

### ISSUE THREAD

**Issue by jos-rosenqvist-3812** [lunduniversity/introprog#235]
The examples in the `bank` project use IDs that are written like Swedish personal identity numbers, e.g. 6707071234. Many such IDs (in particular, the ones for people born between 1922 and 1999) are too large to fit in `Int`s, but the specification of `Customer` says that IDs need to be stored as `Int`s.

**Comment by bjornregnell** [comment]
A very relevant issue. Better to store them as Long. PR  welcome ;)

**Comment by bjornregnell** [comment]
Good catch! Yes, it would be better to store id nums in a Long. PR welcome ;)

**Comment by bjornregnell** [comment]
But on the other hand maybe better to wait to fix this. Bank probably needs a complete redesign from scratch....

**Comment by jos-rosenqvist-3812** [comment]
@bjornregnell Have we decided yet whether we should redesign bank? There are only a few weeks left until the new compendiums are going to be printed...

**Comment by bjornregnell** [comment]
I'm unsure if I'll make it as I'm swamped. If you see easy fixes PR:s are welcome. I guess a complete re-design is not feasible for me given my work load until printing deadline; so feel free to polish it in whatever direction you find feasible an provide PR:s if possible...

**Comment by jos-rosenqvist-3812** [comment]
I'll try to make the instructions clearer and fix errors like this one, then. I'll avoid changing the number of things that need to be implemented since I don't know what reductions could be appropriate for that, but I suppose it's not too much of an issue for the bank project to have a higher difficulty level than the other projects as long as we make that clear to the students (unlike last year).
