### ISSUE TITLE
Make changes in compendium and solutions?

### ISSUE THREAD

**Issue by saranyberg** [lunduniversity/introprog#253]
During the autumn I made a note whenever I found a typo or a fault in a solution (as far as I could understand - often that solutions to sub-tasks were missing or mixed up). So should I do the process of creating a fork, commit and pull request? Or can I just make comments in downloaded PDF-file of compendium and solution and send it to Björn? I would like to help out, but I haven't worked with git before - I just read the instructions about how to commit and send pull requests, which seems doable, but all new to me.
Then I also think I found a mistake in one of the slides; w3 - part about Funktioner - title: "Funktionsvärden kan vara argument" (slide 139): Since you apply the function two times, the value should be 44 and 40 (and then 44 again), shouldn't it?
/ Sara

**Comment by ErikBjare** [comment]
@saranyberg Great that you've collected notes with corrections! We will happily include them.

You should go ahead and create a fork, make the changes and then create a pull-request. That way you get credit where credit is due. Feel free to include corrections to the slides as well. I haven't taken a look at the specific place you mentioned but it will all be subject to review when the pull-request is made so if you think something is wrong, don't be afraid to correct it (in the case that the correction is wrong, it will be caught in the review).

If you need any help, just drop a comment in this issue or send me an email at erik@bjareho.lt

Happy to have you as a contributor :smile:

**Comment by bjornregnell** [comment]
If you make fixes @saranyberg don't hesitate to send PR:s - I'm closing this issue now, but open new ones on fixes that might need discussion, or else just go ahead and send PR.

**Comment by saranyberg** [comment]
Ok! I have been busy with my courses and other things so far - but if it's
not too late, I plan to do it in the beginning of June!
/ Sara

**Comment by bjornregnell** [comment]
It's not too late; all input and corrections are welcome at any time! During the coming month I will make some significant changes to the order of modules and also update their contents, so in the beginning of June, you will have to identify the new places for typos and errors, but I hope the table of contents can guide to the right location. Otherwise don't hesitate to contact me and ask about the new structure.
