### ISSUE TITLE
lab kojo: ready for inspection and test

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#267]
Feedback welcome in this discussion thread! (Ok to write in Swedish or mix English/Swedish in this thread if you feel that it makes the discussion easier)

Kojo is now updated based on experiences from last year. Now, should be: 
* Less mandatory work (several tasks moved to non-mandatory section)
* More freedom
* Many minor edits

**Comment by Martomate** [comment]
The code for task number 8 on page 44 is on the next page. Not a big problem since it's among the extra tasks, but it's refered to as being "above" in the b-subtask.

**Comment by bjornregnell** [comment]
Thanks @Martomate !! Fixed in this commit: https://github.com/lunduniversity/introprog/commit/97e6a187cdcb8fe622df8097298a392245edd900 

This happens to be commit number 2000 which is a great achievement for this repo.  :1st_place_medal: :)

Next time perhaps you are able to make the change and contribute with a pull request...
