### ISSUE TITLE
lab shuffle: ready for inspection and test

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#268]
Feedback welcome in this discussion thread! (Ok to write in Swedish or mix English/Swedish in this thread if you feel that it makes the discussion easier)

lab shuffle is now updated based on experiences from last year. Now, should be:
* Refactor to use sequences instead of map to align with new progression
* More Scala-idiomatic
* Mutable members made private
* Use Vector instead of Array when possible
* Simplified and more readable code
* Separation of concerns: Hand now does what belongs to hand etc.
* Added relevant companion object members etc.
* Many minor edits

**Comment by MechaMagpie** [comment]
These all look like very sensible changes

**Comment by bjornregnell** [comment]
@MechaMagpie Nice to know, thanks for checking.
