### ISSUE TITLE
 lab words: ready for inspection and test 

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#269]
Feedback welcome in this discussion thread! (Ok to write in Swedish or mix English/Swedish in this thread if you feel that it makes the discussion easier)

lab **words** replacing *pirates* is now available based on experiences from last year. Feedback welcome on these matters:

* Is it easier to know what to do compared to old lab?
* Is the required effort in mandatory tasks ok?
* Is the given code easy to understand wrt naming of methods, given pseudo-code etc?

**Comment by Sebergo** [comment]
Gjorde labben idag. 
I helhet var labben bra, behöll det roligaste ifrån pirates labben.

Tyckte dock den var otydlig på vissa ställen.

apply metoden i uppgift 1 förklaras aldrig. Jag tycker ej det är tillräckligt tydligt vad denna metod ska göra.
Hade velat ha en liten komentar // skapar en ny FreqMapBuilder och lägger till alla strängar i den. 
Ifall detta är första gången som String* parametrar används så behöver det förklaras

när jag skriver strängar i min REPL i intellij så gillar den inte åäö så fick:
Vector(gurka, r, ingen, tomat, men, gurka, r, en, gr, nsak)
som resultat i repl testet. Funkar kanske på skoldatorerna? kanske inte är viktigt.

blev förvirrad av bigrams, läste det varje gång som big-rams, kanske ska heta biGrams och nGrams?

uppgift3 metoden wordfreq förklaras aldrig. Man måste via association ta reda på vad den gör.

i uppgift 5 så är psuedo koden väldigt nära den faktiska koden, desutom så är det nästan samma sak som man behövt göra i add() i FreqMapBuilder, så hade nästan varit mer lämpligt med psuedokod till den metoden istället.

uppgift 6 känns väldigt flummig. Tycker att man åtmistånde måste specifiera ett minimum antal mått man måste rapportera. Förstog heller inte om man var tvungen att kunna acceptera både URLs och filnamn, ifall man måste det så är det ganska svårt, då måste man göra felhantering eller filhantering för att klara av det, känns för mycket för en liten flummuppgit i slutet av labben.

gillar hur labben är uppbyggd, dvs stegen är lagom stora. känner generellt genom labben att beskrivningarna kunde varit längre eller att alla funktioner skulle ha kommentarer.

gillar det nya uppläget av att använda repl för debugga, 

Vet tyvärr ej hur lång tid labben tar då jag åt kvällsmat halvägs igenom, men känns som den borde vara överkommlig på 2 timmar.

**Comment by jos-rosenqvist-3812** [comment]
Definitivt trevligare än pirates, tycker jag!

Jag gjorde de obligatoriska delarna av labben idag på en av skoldatorerna, och det var inga som helst problem med åäö. Jag körde det helt i terminalen eftersom jag antog att det var så det kommer göras när kursen körs på riktigt i höst. Det enda som var lite störigt med det var att man behövde starta om REPLen och därmed förlora historik/variabler/`import nlp._` varje gång man kompilerade om något, men jag antar att det inte finns så mycket att göra åt det.

Jag håller med om att `apply` i uppgift 1 känns otydlig. Hade jag fått välja en enda sak att ändra med labben så hade det varit att förklara den funktionen bättre.

@Sebergo har en poäng med pseudokoden till uppgift 5, men jag håller inte med om att byta ut den pseudokoden mot pseudokod för `add`. För det första så går det att skriva `add` på ett snyggt sätt utan if-sats, och även om en hel del kommer skriva `add` med if-sats tycker jag att det är trevligt att ge folk möjligheten att själv komma på icke-if-lösningen istället för att vi mer eller mindre säger att man ska göra det på ett visst sätt. För det andra är hela grejen med strukturer inne i strukturer något som verkligen ställde till det för folk i pirates, så vi behöver ha en bra förklaring i uppgift 5, och det tycker jag att den nuvarande pseudokoden hjälper till med.

Att acceptera både URLer och filnamn i uppgift 6 är inte så svårt om man använder den halvfärdiga Main-koden som redan finns i workspacet, men på labben låter det mer som att man ska skriva ett eget Main istället... Borde vi kanske omformulera uppgiftsbeskrivningen så att det står att det räcker att implementera `top` i den existerande Main-koden men att man (frivilligt) får göra mer om man vill?

**Comment by bjornregnell** [comment]
@Sebergo @jos-rosenqvist-3812 Stort tack för konstruktiva kommentarer! Skönt att höra att det är en förbättring :)

* Vi kommer troligen att vänta med IDE till lp2. 

* Jag har inte bestämt hur mycket som ska vara givet av Main i workspace, men där visas nu hur man löser url/filnamn-problemet på ett smidigt sätt. 

* Tanke med uppgift 6 var att avsluta den obl. delen med en öppen uppgift så att folk kan anpassa ambitionsnivån efter eget huvud och tiden/orken som det råkar ha kvar. @Sebergo Gillar du inte det (för "flummigt"?) och tycker att den borde vara helt "stängd" i stället?

* bigram är faktiskt ett ord även om bigRAM är ngt helt annat :) https://en.wikipedia.org/wiki/Bigram

**Comment by bjornregnell** [comment]
BTW: Anledningen att jag har både fromURL och fromFile är att om det blir slött under labben för att alla ska ladda ner hela tiden från samma server så ska man kunna köra på en lokal fil också...

**Comment by bjornregnell** [comment]
@jos-rosenqvist-3812 Så slipper du upprepa din import: starta RELP med scala -i <initfil>
```
$ cat >init.sc
import scala.util.Random
$ scala -i init.sc
Welcome to Scala 2.11.11 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> Random
res0: scala.util.Random.type = scala.util.Random$@33aeca0b
```

**Comment by bjornregnell** [comment]
Har lagt in main-exempel i labben nu och fixat förklaring av apply. OK nu?

**Comment by bjornregnell** [comment]
Closing this for now; will reopen if you find something in new version.
