### ISSUE TITLE
W01 - solutions for exercises 6a and 6b are in the wrong order

### ISSUE THREAD

**Issue by davidsoederberg** [lunduniversity/introprog#284]
The exercises are in this order:

> Uppgift 6. Matematiska funktioner. Scaladoc.
> **a)** Antag att du har ett schackbräde med 64 rutor. Tänk dig att du börjar med ett enda
> riskorn på första rutan och sedan lägger dubbelt så många riskorn i en ny hög ..... 

> **b)** Definiera funktionen omkrets nedan i REPL. Går det bra att utelämna returtyp-annoteringen?
> Varför? Finns det anledning att ha den kvar?
> `def omkrets(radie: Double): Double = 2 * math.Pi * radie`

The solutions are in this order:

> **a)** Ja, returtyp-annoteringen : Double kan utelämnas.
> • Varför kan returtyp utelämnas?
> Eftersom kompilatorns typhärledning kan härleda returtypen.
> • Varför kan man vilja utelämna den? ...

> **b)** Beräkning av 264 −1 med math.pow enligt nedan ger ungefär 1.8·1019
> ```
> 1 scala> math.pow(2, 64) - 1
> 2 res0: Double = 1.8446744073709552E19
> ```

**Comment by bjornregnell** [comment]
Thanks for spotting this. Now merged!
