### ISSUE TITLE
Solution for exercise 5c in week 7 (lookup) is out of date

### ISSUE THREAD

**Issue by jos-rosenqvist-3812** [lunduniversity/introprog#300]
The solution for exercise 5c in week 7 refers to http://docs.scala-lang.org/sips/completed/trailing-commas.html as something that will be added in the future, but it has already been added in the version of Scala that we're using for the current instance of the course. (Maybe the task itself needs to be changed as well, since students might write the code on more than one line and thus not get any compilation error...)

**Comment by bjornregnell** [comment]
Aha!! Thanks for the info, I had the expression that it had to wait until 2.13!
This is Nice. PR welcome to remove this twist  or explain that it came into scala 2.12.2 or whatever. Good catch!! Found this link that we could refer to in the solution if you think it is relevant:
http://docs.scala-lang.org/sips/completed/trailing-commas.html

**Comment by bjornregnell** [comment]
Easiest is to just remove it. More work: to transform it to show the full story of when trailing commas are allowed etc and move it to fördjupningsuppgifter. You decide. If you delete it, then make an issue of that an exercise on trailing commas could be added.
