### ISSUE TITLE
lab maze: walk-method could be implemented with minor errors

### ISSUE THREAD

**Issue by VictorWinberg** [lunduniversity/introprog#326]
The algorithm students implement in method `walk` in `MazeWalker` allows the students to do I minor error when checking `isWallAtLeft` and `isWallInFront`.

`if !isWallAtLeft`
 - we know that there is a empty space to the left 
 - therefore we can turn AND move the turtle to the left

However `if isWallInFront`
 - we know that we need to turn right
 - BUT we can not move the turtle in that direction
 - because `isWallInFront` does not tell us `!isWallAtRight`

An example where the turtle should walk through the wall, if the turtle also moves in the right direction, is when it walks into a dead end and needs to perform a U-turn.

We could perhaps check if this error occurs by ...
 - ... writing a test for the dead end case
 - ... changing the turtle move `length` to the maze `blockSize`

**Comment by jos-rosenqvist-3812** [comment]
I don't think it's reasonable to require that this works correctly, since one pixel wide dead ends never can occur under the conditions of the lab.

**Comment by bjornregnell** [comment]
maze is deprecated
