### ISSUE TITLE
fix static Hangman.java and JShowInt.java

### ISSUE THREAD

**Issue by VictorWinberg** [lunduniversity/introprog#338]
Why is these two java classes: [Hangman.java](https://github.com/lunduniversity/introprog/blob/master/compendium/examples/scalajava/Hangman.java) and [JShowInt.java](https://github.com/lunduniversity/introprog/blob/master/compendium/examples/scalajava/JShowInt.java) like singleton static-only objects?

I think it is more correct instantiating the classes in the `main` method rather than making it singleton, i.e., in `main` writing `new Hangman().play`. However in the case for Hangman the download method could still be static, i.e., `new Hangman().play(Hangman.download(...))`.

Just as the case for `Scanner` you will instantiate the scanner by `new Scanner(System.in)` I think that they should learn instantiating their own classes.

**Comment by bjornregnell** [comment]
There are other classes without static later so I think this a minor problem. Also in the javatext lab the ganme is required to be restarted so they need to take this step there. So i'm inclined to keep this as is.
