### ISSUE TITLE
Fix the bug in task 1 c) of the project life

### ISSUE THREAD

**Issue by JohannesTykesson** [lunduniversity/introprog#340]
In task 1 c) of the project [Life](https://github.com/lunduniversity/introprog/blob/master/compendium/modules/w13-assignment-life.tex), the description says that you should try your code with the method randomize and send an integer 2 as a parameter. However the method randomize implemented in the trait [Matrix2D](https://github.com/lunduniversity/introprog/blob/master/workspace/w13_life/src/main/scala/models/Matrix2D.scala) does not take any parameters.

**Comment by bjornregnell** [comment]
Life project is now retired and replaced with lab life. Closing this in consequence. That's life :)
