### ISSUE TITLE
Project instructions and documentation appendix are not available in compendium 2

### ISSUE THREAD

**Issue by jos-rosenqvist-3812** [lunduniversity/introprog#343]
It's unfortunate that the project instructions (the instructions that aren't specific to a particular project choice) and the javadoc/scaladoc instructions aren't available in compendium 2, since many students won't have access to compendium 1 when doing the project (unless they download the PDF). I don't know if making a copy of the project instructions in compendium 2 would make perfect sense (it would look weird to have just that one page and not the rest of the chapter that it's in), but I do think it would make sense to have the javadoc/scaladoc appendix in compendium 2 instead of compendium 1.

**Comment by bjornregnell** [comment]
I'll skip to include a duplicate that will increase printing costs. The pdf is available online... I also want to keep the doc appendix in part one as it tells about how to read docs which they need early on. We can always help them to point to the mega compendium.pdf with everything.
