### ISSUE TITLE
Comments in life are not appropriate for scaladoc

### ISSUE THREAD

**Issue by jos-rosenqvist-3812** [lunduniversity/introprog#345]
The comments in the given code for the life project do not work well with scaladoc, for two reasons:

* They use `//` comments instead of `/**` comments.
* If you change the `//` comments above methods to `/**` comments, you have the problem that the comments describe both the public interface and hints on how to implement the methods, which is not appropriate for generating documentation of the public interface.

**Comment by bjornregnell** [comment]
Life project is now retired and replaced with lab life. Closing this in consequence. That's life :)
