### ISSUE TITLE
life is short

### ISSUE THREAD

**Issue by jos-rosenqvist-3812** [lunduniversity/introprog#346]
Since `life` originally was designed as a lab rather than a project, its length is shorter than that of the other projects. Last year when `life` was turned into a project, we added a rule that you had to do one of the optional tasks of `life` if you wanted to do it as your project. However, I haven't heard anything about that rule being in place this year, so I'm wondering if it isn't a bit too short this year... For next year, should we explicitly write in the `life` project description that you have to do one of the optional tasks, or maybe add more things to the mandatory tasks?

**Comment by jos-rosenqvist-3812** [comment]
Or maybe `life` actually is close enough in length to one of the other projects? I haven't done all of them completely, so I don't know the exact lengths of them.

**Comment by bjornregnell** [comment]
We need to rethink the projects to next year. I guess there is some compelling arguments to only have one project... Maybe life is a bit simple but we'll leave it so for now.

**Comment by bjornregnell** [comment]
Closing this as the old project is replaced by a completely reworked lab.
