### ISSUE TITLE
tictactoe: eval comment is misleading if playfield is not inverted

### ISSUE THREAD

**Issue by jos-rosenqvist-3812** [lunduniversity/introprog#347]
A footnote in task 1 of tictactoe says that you have to either invert the playfield when sending it to player 2 or make the players keep track of whether they're `-1` or `1`. However, the comment above `eval` assumes that you've done the former:

```
* who is 1 if it's this player's turn to make a move,
* -1 if it's the opponent's turn to make a move. 
* From move, eval should be called with who = -1.
```

Since `eval` is very hard to understand, this can cause a lot of trouble.

---

As a side problem, a footnote in task 1 might not be a good place to place the text about inverting the playfield or making players keep track of who they are. This information is very important, so it shouldn't be printed in a way that makes it easy to skip over. And we should probably either move the information later into the text or clarify why inverting/tracking is needed, since it actually doesn't matter before starting with task 3.

**Comment by bjornregnell** [comment]
tic-tac-toe is "retired" so closing this.
