### ISSUE TITLE
Neighborhood metrics described incorrectly in Life

### ISSUE THREAD

**Issue by MechaMagpie** [lunduniversity/introprog#348]
Related to #345, comments in  [Matrix2D](https://github.com/lunduniversity/introprog/blob/master/workspace/w13_life/src/main/scala/models/Matrix2D.scala) associate Manhattan distance with the Moore neighborhood; Chebyshev distance with the von Neumann neighborhood. 
These should be the other way around, i.e. 
* Moore neighbor → Chebyshev distance < 1 
* von Neumann neighbor → Manhattan distance < 1

**Comment by bjornregnell** [comment]
This is not relevant anymore as the old life project is replace by a completely reworked lab.
