### ISSUE TITLE
blockmole: Coordinate conversion in block function is often ignored

### ISSUE THREAD

**Issue by jos-rosenqvist-3812** [lunduniversity/introprog#375]
Many people who did the blockmole lab didn't realize that coordinate conversion was intended to be done in the `block` function (though they didn't seem to have too much trouble figuring out *how* to do coordinate conversion – some students had done it in the code that called `block`). Is there a good way for us to clarify this further?

**Comment by bjornregnell** [comment]
@jos-rosenqvist-3812 Is this a good fix? Otherwise re-open and comment. https://github.com/lunduniversity/introprog/commit/621d66e5e079ccc3290d0e156a2c04ccbf057d06

**Comment by jos-rosenqvist-3812** [comment]
I believe that that change combined with PR #452 will make it unlikely for people to mess it up. So I'm fine with closing this issue.
