### ISSUE TITLE
[Question] Can Try in hangman.download of return a None?

### ISSUE THREAD

**Issue by wanecek** [lunduniversity/introprog#390]
In the finished example code in the idiomatic scala version of Hangman, [`hangman2.scala`](https://github.com/lunduniversity/introprog/blob/master/compendium/examples/scalajava/hangman2.scala), one apparent change from `hangman1.scala` is that [`hangman.download`](https://github.com/lunduniversity/introprog/blob/master/compendium/examples/scalajava/hangman2.scala#L23-L32) returns an `Option[String]`.

```scala
def download(address: String, coding: String): Option[String] = 
  scala.util.Try {
    import scala.io.Source.fromURL   
    val words = fromURL(address, coding).getLines.toVector
    val rnd = (math.random * words.size).toInt
    words(rnd)
  }.recover{ case e: Exception =>  
    println(s"Error: $e")
    "lackalänga"
  }.toOption
```

and the result is extracted through a foreach, i.e. [`download(url, codec).foreach(play)`.](https://github.com/lunduniversity/introprog/blob/master/compendium/examples/scalajava/hangman2.scala#L55)

As far as I see it, the possible outcomes are:

- The Try-block succeeds, and a string is returned (even if it's an empty string)
- The Try-block throws, and recovers with a fallback string (network request fails, file is empty (index overflow), etc)

Is there any scenario where `download` returns `None`? If so, how? And if not, would it make sense to `.get` the `Success`/`Failure`, instead of converting it to an `Option`, i.e. something along the lines of:

```scala
def download(address: String, coding: String): String =  // Changed to String
  scala.util.Try {
    import scala.io.Source.fromURL   
    val words = fromURL(address, coding).getLines.toVector
    val rnd = (math.random * words.size).toInt
    words(rnd)
  }.recover{ case e: Exception =>  
    println(s"Error: $e")
    "lackalänga"
  }.get // changed to .get
}
```

In the lab instructions, the following can be read:
> Låt metoden download returnera en Option[String] som i fallet att nedladdningen
misslyckas returnerar None.

However, as far as I can tell, that's not true - a failed download will either throw a `java.io.FileNotFoundException`, or, if the file is empty, throw an error when trying to access `words(rnd)`.

--- 

_I fully understand that there always are several ways to achieve a goal, often without one necessarily being better than the others. This seems to be especially true in Scala. I'm mostly curious to if I'm missing any of the outcomes of download, or if it's more idiomatic to use Option wherever possible._

**Comment by bjornregnell** [comment]
Yes, this is a "bug". Better to skip recover and convert the Try to an Option (and thus avoid get). It would be great if you could check if other code is unaffected by such and if so come with a tested pull request?

**Comment by bjornregnell** [comment]
I also want to avoid the side-effecting print if it does not break any other exercise or similar.

**Comment by wanecek** [comment]
Great, thanks for letting me know! I'll gladly try to cook something together by next week :+1:
