### ISSUE TITLE
Fix Bank Rollback Date, add date in doEvent

### ISSUE THREAD

**Issue by Rara1212** [lunduniversity/introprog#397]
When trying to rebuild with `returnToState`, `doEvent` needs the old Date or else it should use current time.
```scala
def doEvent(event: BankEvent, historyDate: Date = Date.now()): String
```

**Comment by jos-rosenqvist-3812** [comment]
The public method `doEvent` should not allow callers to pick a date. You can however have a private `doEvent(event: BankEvent, historyDate: Date)` in addition to a public `doEvent(event: BankEvent)` if you want to. (It is also possible to solve the `returnToState` problem without adding a `Date` parameter, but I will not go into detail about that.)
