### ISSUE TITLE
Reference to a deleted Wikipedia page about Java hashCode()

### ISSUE THREAD

**Issue by AntiSC2** [lunduniversity/introprog#416]
In chapter 6, at the end of exercise 12, there is a reference to the wikipedia page: https://en.wikipedia.org/wiki/Java_hashCode()

That page [is now deleted](https://en.wikipedia.org/w/index.php?title=Special:Log/delete&page=Java_hashCode()) for the following reason:

> Expired PROD, concern was: Individual Java methods are not encyclopedic content. This topic is certainly covered in a number of sources; however, this coverage is in a sense routine. Every single built-in function in the language is thoroughly described in documentation and reference books. Yet this does not make then notable enough for an article.Further, this article is a concerning mix of information on general hash functions and their usage with Java-specific d

Therefore, the reference should be replaced by another.

**Comment by bjornregnell** [comment]
Good Catch. Would you perhaps like to do a pull-request with some updated reference?

**Comment by bjornregnell** [comment]
Fixed by https://github.com/lunduniversity/introprog/commit/c3cee77534c4d27213c5b6e5c1dc64bdb4eda1ea
