### ISSUE TITLE
Students do not understand why KeyControl should be implemented

### ISSUE THREAD

**Issue by emilwihlander** [lunduniversity/introprog#417]
In the exercise classes, in chapter 5, the students are prompted to implement the case class KeyControl. My experience is that they struggle to understand why and therefore need help.

This could be solved by explaining how it will be used later on.

**Comment by hnrklssn** [comment]
This is my experience as well. Potentially you could make the instructions not mention KeyControl initially and have them hardcode the keys in Mole, making them all move in sync to the same inputs. Then after they have realised that a better way is needed, make them abstract it away with KeyControl.
