### ISSUE TITLE
improve BlockBattle instruction and doc of methods

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#421]
Explain and document given code. Consider rename eraseBlocks to redraw blocks. BackgroundColorAtDepth etc, Comments welcome.

**Comment by OliverPerssonB** [comment]
One economical edit is simply adding a comment line, like the on in update bellow, saying something like "Use to erase old points". This can also be done in the colorAtDepth method, giving more hints to the purpose of the function.

**Comment by bjornregnell** [comment]
@OliverPerssonB  Would you be prepared to makes this simple fix in a PR?

**Comment by OliverPerssonB** [comment]
Yes, I will fix it during the week.
