### ISSUE TITLE
lab life check if copy method is really needed

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#426]
There is a tip in the lab life to use copy on a case class but there is only one class parameter so it does not make much sense, or?

**Comment by bjornregnell** [comment]
The implementation can be 
```scala
def updated(row: Int, col: Int, value: Boolean): Life =   copy(cells = cells.updated(row,col)(value))
```
or
```scala
def updated(row: Int, col: Int, value: Boolean): Life =   Life(cells.updated(row,col)(value))
```
so the method copy does not help much.
I will remove the tip.

**Comment by bjornregnell** [comment]
@jos-rosenqvist-3812  here is a fix https://github.com/lunduniversity/introprog/commit/53cac3b611aabbe922c62e3283255aa34c490be4 -- let me know if there are any problems or else this can be closed.

**Comment by jos-rosenqvist-3812** [comment]
Looks good to me.
