### ISSUE TITLE
implement JFrame.setTitle in PixelWindow

### ISSUE THREAD

**Issue by ke8683da** [lunduniversity/introprog#428]
I am requesting the setTitle method to be implemented and accessible from introprog.PixelWindow. I noticed that JFrame has a method for renaming the frame title, and I am missing this feature in PixelWindow, it could be useful

**Comment by bjornregnell** [comment]
Nice idea! This issue should go to the introprog-scalalib repo. Could you re-create this issue there? It would also be great if you could fork it and create a pull request?

**Comment by bjornregnell** [comment]
https://github.com/lunduniversity/introprog-scalalib
