### ISSUE TITLE
Odd phrasing in instructions for lab w09 (words)

### ISSUE THREAD

**Issue by elliotbrack** [lunduniversity/introprog#430]
The phrase "Är mängden av alla nycklar i en nyckel-värde-tabell garanterat unika?" (9.3.3.4) is difficult to understand - is the set unique, or are the keys unique? Is there any difference in emphasis to the simpler phrasing of 9.3.3.5: "Är alla värden i en nyckel-värde-tabell garanterat unika?"?

**Comment by bjornregnell** [comment]
Good catch! This is a bug. The simpler wording in 9.3.3.5 is good and should be used in 9.3.3.4 as well. Are you willing to go for a pull-request that fixes this?

**Comment by elliotbrack** [comment]
Yes; see PR #434.
