### ISSUE TITLE
Swap "evaluera" for "utvärdera"

### ISSUE THREAD

**Issue by elliotbrack** [lunduniversity/introprog#435]
It sounds like an anglicism and isn't very intuitive, whereas with "utvärdera" it's quite obvious: literally, "[get a] value out [of the expression]". Both are perfectly standard Swedish, and in other cases (uttryck/expression, tilldela/assignera, immutabel/oföränderlig) the Germanic option seems to be preferred.

`grep -or evaluer | wc -l`gives 83 counts, although an automatic search and replace would probably not be a great idea.

**Comment by bjornregnell** [comment]
@elliotbrack Well, you are right that "utvärdera" is more common in ordinary language, but in mathematical language and in programming the term "evaluera" is used exactly for this in typical Swedish,  so I don't think it can be regarded as an anglicism, hence I'm closing this. Thanks anyway for thinking in this direction as we indeed should avoid any unnecessary anglicism if better options exists!
