### ISSUE TITLE
Change "BankKonto" to "Bankkonto" in 4.1.29 (p118)

### ISSUE THREAD

**Issue by elliotbrack** [lunduniversity/introprog#436]
"BankKonto" implies the underlying phrase is "Bank konto," which is definitely not correct. It should be changed to "Bankkonto".

**Comment by elliotbrack** [comment]
Likewise for "UnderPopulated" and "OverPopulated" in the slides for w08, no?

**Comment by bjornregnell** [comment]
@elliotbrack Only BankKonto should be changed. New PR welcome.

**Comment by bjornregnell** [comment]
fixed by 59a9730a83c6759550eb6cff97f6aa16bef2057c
