### ISSUE TITLE
Usage of "bibliotek" (swe. library) for folder/directory

### ISSUE THREAD

**Issue by elliotbrack** [lunduniversity/introprog#437]
Usually, the non-leaf nodes in a file system are called folders or directories, which are called "mappar" or "kataloger" in Swedish by analogy. See for instance http://www.termado.com/DatatermSearch/?ss=folder:
>Använd katalog eller mapp för eng. directory, catalog, catalogue eller folder.

Are "mapp" and "bibliotek" used interchangeably? Is there any difference in emphasis? Is it related to the usage of "bibliotek" for dynamic libraries?

**Comment by jos-rosenqvist-3812** [comment]
I believe the course currently uses "mapp", "katalog" and "bibliotek" interchangeably. It would be nice if we could standardize on one of them – and preferably not "bibliotek", since it's more rarely used and since it might make people mix up directories with the kind of library you mention.

**Comment by bjornregnell** [comment]
Good catch. Should be "katalog" consistently I think, as "mapp" is to similar to `map` which is not a fold(er) :)

**Comment by bjornregnell** [comment]
fixed by 437d97c2d4360c5b09de6d01757ab6d96a5e7f6f
