### ISSUE TITLE
Quickref: what is the difference between a collection "formed" and "obtained"?

### ISSUE THREAD

**Issue by elliotbrack** [lunduniversity/introprog#438]
Example:

`xs map f`A collection formed by applying f to every element in xs.
`xs flatMap f` A collection obtained by applying f (which must return a collection) to all elements in xs and concatenating the results.

**Comment by jos-rosenqvist-3812** [comment]
There is no difference as far as I'm aware.

**Comment by bjornregnell** [comment]
Yes, should be the same wording, e.g. "formed". PR welcome.
