### ISSUE TITLE
Incorrect syntax in compendium

### ISSUE THREAD

**Issue by ke8683da** [lunduniversity/introprog#441]
Page 426 (13.3. PROJEKTUPPGIFT: BANK), under Specification BankAccount and Specification Customer, the initialization of classes are not following proper syntax.

For example:
`case class Customer(name: String, id: Long) = {
override def toString(): String = ???
}`

**Comment by ke8683da** [comment]
PR created - #442

**Comment by bjornregnell** [comment]
PR merged. Thanks!
