### ISSUE TITLE
Make outer parenthesis bold or slightly larger in logic statements to improve readability

### ISSUE THREAD

**Issue by benkibejs** [lunduniversity/introprog#456]
Found it hard to comprehend the logic statement in 1.1.25. If i was writing in mathmode in latex i always use the parenthesis that adapt there size depending on their surroundings, ithink it was simply "\left(" and "\right)" . i have not been using latex in a while and don't have access to proper computer currently so cant fix it myself.
https://github.com/lunduniversity/introprog/blob/635507fb31526515d653ec4694501f77b2a2c09a/slides/body/lect-w01-intro.tex#L697

**Comment by bjornregnell** [comment]
Thanks for working on readability! I deliberately chose the Code environment to make it look like code rather than Latex math, and programming code is filled with nested brackets that we have to live with :). Changing this to a latex math environment is possible, but I'm not sure if it's worth it in this case.

**Comment by benkibejs** [comment]
Considering that it is a sufficiently complex logic statement that i think many people would pull out pen and paper to figure out how to reduce, I'd say the extra clarity is warranted, but then on the other hand i really understand the want to not introduce the mathmode style, that might just confuse the reader, suddenly changing the typeset for what is essentially still code. Not gonna push anymore on this. Will make sure to make issues when i find more readability concerns.

**Comment by bjornregnell** [comment]
OK. Thanks. Closing this for now.
