### ISSUE TITLE
\code{\Vector{}} Does not respect the margin or the end of the line.

### ISSUE THREAD

**Issue by benkibejs** [lunduniversity/introprog#457]
The vector goes to the margin and is not shown properly.

https://github.com/lunduniversity/introprog/blob/635507fb31526515d653ec4694501f77b2a2c09a/compendium/modules/w02-programs-exercise.tex#L453

**Comment by benkibejs** [comment]
Seems to be \code{} that does not properly change lines, found another example in laboration blockmole uppgift 5c)
![Radbryt](https://user-images.githubusercontent.com/5822409/89387925-84234880-d703-11ea-8096-5e923ca23236.png)

**Comment by bjornregnell** [comment]
Thanks for spotting these. Will fix.
Yes, \code intentionally don't break lines as they seldom are broken where you want... When wanting to use normal line breaks, use \texttt or else break manually; this is the policy for now...

**Comment by bjornregnell** [comment]
If you find more of these kinds of bad line breaks, they are very welcome as issues :+1:  Mind that they need to be solkved in a way that is respectful both in print versions compendium1.pdf + compendium2.pdf and in screen version compendium.pdf
