### ISSUE TITLE
Random is referenced earlier in the material withouth beeing introduced

### ISSUE THREAD

**Issue by benkibejs** [lunduniversity/introprog#458]
Random is used/referenced in 3.2.1 Assignment 1&3 and 4.3.4 Assignment 12 (extra assignment). It does not get properly introduced until 7.1.41
https://github.com/lunduniversity/introprog/blob/635507fb31526515d653ec4694501f77b2a2c09a/compendium/modules/w07-sequences-chapter.tex#L16

**Comment by bjornregnell** [comment]
Good catch! A progression bug after reshuffling. I'll think about the best solution when I get to it. Thanks!
