### ISSUE TITLE
The concepts/words "predikat" and "slumptalsfrö" is referenced in an assignment before beeing introduced.

### ISSUE THREAD

**Issue by benkibejs** [lunduniversity/introprog#459]
In 3.2.1 assignment 1 the word "predikat" and "slumptalsfrö" is referenced without being introduced. These are introduced in 7.1.12 and 7.1.41 respectively. The list of concepts being introduced in chapter 3 also includes theese two words, while then not being present in the text.

**Comment by bjornregnell** [comment]
Partly fixed in https://github.com/lunduniversity/introprog/commit/bf44e40279f05cf75c40a1d930e94b2f381bb0d6
