### ISSUE TITLE
4.1 has some incorrect refrerences to scala 1.12 instead of the new scala 1.13.

### ISSUE THREAD

**Issue by benkibejs** [lunduniversity/introprog#461]
In 4.1.38-41 references scala version to 1.12 instead of 1.13 in files and such.

**Comment by bjornregnell** [comment]
I had to fix some inconsistencies to get this right (I hope), see https://github.com/lunduniversity/introprog/commit/e34d2b07a8a73ae2a326b168f5878b1576eb8d82
