### ISSUE TITLE
Duplicated sections.

### ISSUE THREAD

**Issue by benkibejs** [lunduniversity/introprog#464]
Simply duplicated sections in the text.
https://github.com/lunduniversity/introprog/blob/635507fb31526515d653ec4694501f77b2a2c09a/slides/body/lect-w06-matching.tex#L324-L349

**Comment by bjornregnell** [comment]
Well, there is a difference in that all ??? are replaced with values after evaluation. This is a quiz that I run during lectures. So no duplication if I haven't missed something?

**Comment by bjornregnell** [comment]
I'm closing this, as I believe it is a false positive. You are welcome to re-open if I missed something?
