### ISSUE TITLE
Lab Kojo: control question 11, state not explained enough in lectures/material

### ISSUE THREAD

**Issue by bengterik** [lunduniversity/introprog#474]
As voiced by Jos in TA-meeting, students have little knowledge about _tillstånd_ at this stage of the course. Björn suggested either removing the question or dedicating more time to it in earlier lectures.  

Question:
_Vad innebär tillstånd? Förklara och ge exempel._

**Comment by jos-rosenqvist-3812** [comment]
Students were also unsure about a few other terms such as "kontrollstruktur", but "tillstånd" was the one they voiced the most concerns about. They said that they didn't find anything in the first chapter of the compendium that explained what it is.

**Comment by bjornregnell** [comment]
@bengterik @jos-rosenqvist-3812 Do you see any problems with removing q11 and q6? Thirteen questions is enough...

**Comment by jos-rosenqvist-3812** [comment]
That should be fine.

**Comment by bengterik** [comment]
Agreed! Won't have time tomorrow but can do a PR this weekend.
