### ISSUE TITLE
improve stepwise description of irritext lab

### ISSUE THREAD

**Issue by OliverPerssonB** [lunduniversity/introprog#479]
This a suggested adding. For week 3 lab irritext I have created a step wise list the students can follow to easily get on track and finish the lab. I am very open to suggestions. Note! The list needs to be translated to Swedish.

**algorithm irritext**

You = Student

1) You should start with an object that only contains a main method that prints out HelloWorld, i.e start with something that works and does what you think

2) Do the exercises (w2, w3) before starting the lab. There is a lot of examples which will save you time, especially Björn's example AliensOnEarth

3) Formulate what your program should do before starting to program. **Do not start programming before this step.** You will eventually need to do this anyway and if you have already written a lot of code you might need to delete a lot of your work

4) Revise your formulated problem. Will this require a lot of code? If so, then try to reformulate it such that it is not as big. If you have time you can always add to the simpler program

5) When adding a method, recompile and check if it works as intended. By doing this you can always locate the error by Ctrl + Z until it works again. Save your tests in functions so you can call from main. You do this so you do not have to rewrite them later

6) If you have to name a method with a long name, you should probably break it up into smaller methods which do one single thing

**Comment by OliverPerssonB** [comment]
Suggestion on Swedish translation. I switched place on 1 and 2. Some of the points also received extensions and clarifications.


**algoritm irritext**

Du =  student

1) Gör övningarna vecka 2 och vecka 3 **innan** du börjar arbeta med labben. Där finns många exempel och små saker som kommer spara mycket tid, speciellt Björns exempel spel AliensOnEarth

2) Din irritext fil bör från början bara vara ett singelobjekt som innehåller en main metod. I main metoden bör en println ligga som skriver ut något, exempelvis HelloWorld. Du gör detta så att du börjar med ett program som funkar och gör det du tror 

3) Formulera vad ditt program ska göra innan du börjar skriva kod. **Börja inte skriva innan detta steget.** Du kommer behöva göra detta steget oavsett. Om du då redan har skrivit kod så kommer du kanske behöva tag bort en del av det du skrivit

4) Tänk över din programidé. Uppfyller den alla kraven? Kommer det krävas mycket kod? Om det krävs mycket kod, formulera om din idé så att det blir en enklare version av din första. Du kan alltid lägga till fler saker efter att du fått en enklare version att fungera

5) Ha som vana att kompilera vid varje tillägg till programmet. Säg att du skrivit en till metod. Innan du fortsätter med fler nya metoder så kompilera och verifiera att metoden gör det du tänker. Spara gärna dina test i en funktion. Du kan senare återanvända dessa testen och behöver då inte skriva om dem

6) De viktigaste delarna i denna laborationen är att förstå och kunna använda variabler, metoder och main-metod. Det är bra att använda beskrivande namn på variabler och metoder. Om du har en metod som behöver ett långt beskrivande namn så är det nog bra att dela upp den i fler mindre metoder som gör en sak

**Comment by bjornregnell** [comment]
fixed by #645
