### ISSUE TITLE
In Laboration: BlockMole 11.c, BlockWindow.keepOnDigging() might be more suitable in Mole

### ISSUE THREAD

**Issue by frodikarlsson** [lunduniversity/introprog#483]
As _keepOnDigging()_ is an alternate version of _Mole.dig()_, and as part 2 of exercise _11.c_ prompts the student to create _delayMillis_ in _Mole_, perhaps _keepOnDigging()_ would be better suited in _Mole_ rather than _BlockWindow_.

**Comment by emmanuelkring** [comment]
I am quite sure this is a typo. In the solutions `keepOnDigging()` is in the `Mole` object and not in the `BlockWindow` object. Feel free to make a PR if you want to. The relevant file is: compendium/modules/w04-objects-lab.tex.

**Comment by jos-rosenqvist-3812** [comment]
Fixed by PR #485.
