### ISSUE TITLE
Iterable occurs twice in exercise 7 task 3

### ISSUE THREAD

**Issue by jos-rosenqvist-3812** [lunduniversity/introprog#497]
![image](https://user-images.githubusercontent.com/23549784/96166359-2c346980-0f1e-11eb-8605-a6e7eee1d0a5.png)

635507f replaced usages of Traversable with Iterable, but a simple replacement doesn't make much sense in this case, since we end up with two Iterable. What should be done about this task? Having only two items feels like a bit too little for this "matchup" type of task...

**Comment by bjornregnell** [comment]
Yes this is a bit strange. But it actually works in terms of pairing. But it is also strange now when mutable.Seq is default Seq and does not cover all sequence collections. So I suggest removing it by comments - just make % for all lines and write shortly why with link to this issue url. PR welcome.

**Comment by bjornregnell** [comment]
In the future we can make some better concept pairing on the collection hierarchy including mutale immutable or something. BUt there are actually enogh exercises so perhaps not.

**Comment by jos-rosenqvist-3812** [comment]
If we're going to remove the task, I would prefer to wait until the end of the year (or at least the month) so that we don't mess up the task numbering. (For instance, imagine if someone looks in the online compendium and says they need help with task 7, and the TA looks in the paper compendium, where the task numbered 7 is actually a different task...) So I will make this PR later.

**Comment by bjornregnell** [comment]
Very good point! Thanks for thinking deep :+1:
