### ISSUE TITLE
workspace import instructions don't work with IntelliJ 2020

### ISSUE THREAD

**Issue by jos-rosenqvist-3812** [lunduniversity/introprog#507]
The instructions given in the compendium for importing the course workspace into IntelliJ IDEA don't work on the version of IntelliJ IDEA currently installed on LTH's computers. The "import" option and the "open" option in the welcome screen have been merged into one "open or import" option, and trying to open/import the workspace using this option results in IntelliJ IDEA attempting to set up the workspace using sbt and failing with some error message I don't understand, without ever giving the option of choosing an import model. (Please ping me if I should post the exact error message and I'll do it the next time I'm on campus.)

It is possible to import the workspace using the current version of IntelliJ IDEA, but it requires you to use Ctrl+Shift+A from the welcome screen, which is very unintuitive: https://www.jetbrains.com/help/idea/import-project-from-eclipse-page-1.html

At first I was going to suggest updating the instructions in the compendium to match how the new version of IntelliJ IDEA works, but on second thought, wouldn't it be better to drop the Eclipse model and try to set up sbt so that IntelliJ IDEA will be able to open the workspace cleanly using the "open or import" option? Eclipse is already "deprecated" for this course, and next year would probably be a good time to drop support for it.

**Comment by bjornregnell** [comment]
The eclipse stuff is deprecated from this repo.I have now removed the import instructions from the appendix and linked to the pages of intellij. Could someone with IntelliJ check if we still need to write some instructions on how to import the workspace if it is still unintuitive?

**Comment by bjornregnell** [comment]
Th instructions on workspace import for IntelliJ are gone
