### ISSUE TITLE
w13 project: Add scaladoc to list of requirements

### ISSUE THREAD

**Issue by emmanuelkring** [lunduniversity/introprog#516]
It is very unclear if it is a requirement to generate documentation for the projects in w13. It is only listed as an exercise in "13.2 Övning examprep". 

Generating documentation should be added as a requirement and as an assignment in each of the projects. It should also be clear what is considered adequate documentation. For example that the methods defined by the student are at least listed in the documentation if they are public.

**Comment by bjornregnell** [comment]
This is depending on the availablility of Scaladoc for Scala 3 in `scala-cli` or `sbt`. Needs some investigation.
