### ISSUE TITLE
fix ImageProcessing project to not depend on SimpleWindow

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#520]
Currenlty there is no good way for an introprog.PixelWindow to display a bitmap image as SimpleWindow can. See  #519
We should consider adapting the project ImageProcessing, if kept, to not depending on SimpleWindow and also to extend introprog.PixelWindow with display bitmap image capabilities.

**Comment by jos-rosenqvist-3812** [comment]
It would be nice to be able to drop cslib entirely from imageprocessing. Perhaps if we get rid of the SimpleWindow dependency then we could ship a copy of ImageFilter.java in the workspace instead of shipping all of cslib.

**Comment by bjornregnell** [comment]
Yes, indeed! And we could even translate ImageFilter to Scala.

Se also https://github.com/lunduniversity/introprog-scalalib/issues/13

**Comment by bjornregnell** [comment]
Here is an interesting approach to model Image as a function from locations to colors:
https://adrian-salajan.github.io/blog/2021/01/25/images-functor
Perhaps that can be used in the ImageProcessing project in a simplified version (with out the Functor from the Cats library).

**Comment by bjornregnell** [comment]
@theolundqvist Can you investigate how this impacts the actual project instructions and given code?

**Comment by bjornregnell** [comment]
@DagHemberg Would you be willing to review an updated project if @theolundvist is assigned?

**Comment by theolundqvist** [comment]
> @theolundqvist Can you investigate how this impacts the actual project instructions and given code?

I see, when doing the Image project I drew every pixel individually using PixelWindow.SetPixel. It would definitely be less confusing implementing image drawing capability in PixelWindow.

Shipping ImageFilter.scala with w13_img_proj and adding img drawing capabilities to PixelWindow would simplify project instructions. Changes are required in exercise 1 and ImageFilter class explanation exclusively.

Would like to add "extra task" nr 3; applying filters one after another and undoing unwanted changes.
Not too hard to do, my implementation could probably use some further thought/refactoring.

**Comment by theolundqvist** [comment]
introprog-scalalib is updated

**Comment by bjornregnell** [comment]
now fixed
