### ISSUE TITLE
m1 mac: installing dotty using brew will fail

### ISSUE THREAD

**Issue by fritjof-b** [lunduniversity/introprog#524]
`brew install` uses a ruby file. This ruby file specifies the following dependency 

```ruby
depends_on "openjdk@8"
```

openjdk@8 is not available on M1 Macs yet. Scala should work with other JDK, but the installation will fail regardless if a JDK is installed or not. The problem can be bypassed by installing a suitable JDK manually. And installing via:

```
brew install --ignore-dependencies lampepfl/brew/dotty
```

Fix: wait for openjdk@8 to become available for M1 or underlying Ruby file to change.

**Comment by bjornregnell** [comment]
Thanks! Good to know that there is a work-around. 

This seems like a general problem for the macos platform. Could you check if there are any words from Apple or openjdk/Oracle out there on if | when this might be addressed? I guess many many are in need of openjdk@8 on apple boxes so there is a good chance that this is already discussed in the open...

**Comment by fritjof-b** [comment]
From what I read while investigating there should be an OpenJDK 8 available for Mac M1 soon. There is an OpenJDK 11 available for M1 through brew which I'm currently using - so far it is working just fine for Scala 3.

Some of it discussed here: 

https://stackoverflow.com/questions/64788005/java-jdk-for-apple-m1-chip

**Comment by bjornregnell** [comment]
Aha! We will recommend JDK 11 for students, so perhaps the instructions to install scala on macos anyway should include a first step to install apenjdk@11. I also assume brew will eventually not call it "dotty" but scala@3 or something. Let's revisit this in august and see how things materialize.

**Comment by bjornregnell** [comment]
brew seems fixed. will check this when addressing/testing #557
