### ISSUE TITLE
Appendix H: Add more detailed instructions for VS code

### ISSUE THREAD

**Issue by sadphi** [lunduniversity/introprog#525]
Currently in the compendium, the appendix shortly mentions Visual Studio Code as an editor/light-weight IDE, however there aren't any instructions for downloading and setting up VS Code to work with Scala and sbt, except a brief mention of Scala metals.

Since VS code seems to be pretty popular amongst students, both in the course and in general, the description should be expanded to add install instructions for both VS code and metals (including `build.sbt`).

I can assign myself to this if there is any interest of adding it.

**Comment by bjornregnell** [comment]
Yes, this should be expanded in line with what you suggest. Please assign yourself, but before doing anything I need to restructure the appendices for 2021. Ping me in a week or so if I haven't gotten back to you. Then we can discuss the scope of the expansion. Also Eclipse should be deprecated and commented away.  Meanwhile you fork the repo and try to build it locally with sbt and latex. Let me knwo if you run into problems. Are you on ubuntu?

**Comment by sadphi** [comment]
Sounds good!

**Comment by bjornregnell** [comment]
see also #508

**Comment by sadphi** [comment]
Fixed in [`3dc168e`](https://github.com/lunduniversity/introprog/commit/3dc168ec51ebe35b0a5a0e2641e826aeae736642)

**Comment by bjornregnell** [comment]
Thanks @sadphi for spotting that this should be closed!
