### ISSUE TITLE
Preferred way to create a empty Array of specified size?

### ISSUE THREAD

**Issue by emilwihlander** [lunduniversity/introprog#53]
I know two ways to complete the task:

1. val x = new Array[Int]\(10)
    console: "x: Array[Int] = Array(0, 0, 0, 0, 0, 0, 0, 0, 0, 0)"

2. val x = Array.ofDim[Int]\(10)
    console: "x: Array[Int] = Array(0, 0, 0, 0, 0, 0, 0, 0, 0, 0)"

Which one is preferred in this project?

**Comment by bjornregnell** [comment]
Prefer the second over these two as we then avoid explicit memory allocation with the 'new' keyword, but even better: val xs = Array.fill(10)(0)
I think this is better as the init value is explicit. 
See also: http://stackoverflow.com/questions/3881013/array-initializing-in-scala

In situations when the student is ready for it, I want to show many different ways of doing things and discussion pros/cons/similarities etc. ... but if you just want to find the "recommended" way, use the fill method that works on all collections. With this method you can pass a block that gets evaluated for each fill, e.g. val xs = Vector.fill(10000)(math.random)
