### ISSUE TITLE
Migrate exercise w06 patterns to Scala 3

### ISSUE THREAD

**Issue by alfredgrip** [lunduniversity/introprog#533]
I've made a fork where I have begun migrating code to Scala 3, however...

In exercise 3.b the student is instructed to press tab twice. Using the old scala 2 repl, this would have given the right outcome whilst the new `scala3-repl` doesn't give the right outcome. The exercise instructions should therefore be rewritten if the `scala3-repl` is to be used by students.

In exercise 3.c, the returned value is no longer `Some((100, true))`, instead the value `Gurka(100, true)` is returned when working in the `scala3-repl`. I guess the solution should be changed to match the new outcome?

In exercise 4 the student is instructed to enter `:pa` to the repl to enter paste mode, while this doesn't seem to be a feature of the `scala3-repl`. Also, it seems that the behaviour of `sealed trait` in `scala3-repl` has changed from the old repl. No longer are you able to extend a sealed trait defined in the repl (bug or feature?): 
```
scala> sealed trait Färg
// defined trait Färg
scala> case object Spader extends Färg
1 |case object Spader extends Färg
  |            ^
  |            Cannot extend sealed trait Färg in a different source file
```
It works if you change `sealed trait` to just `trait`, if this is a desired solution then the instruction of the task must be rewritten.
If you change to just `trait` however, subtask 4.b is no longer relevant, since then there is no warning of a case missing. Also subtask 4.d loses its purpose of explaining the keyword `sealed`.

**Comment by bjornregnell** [comment]
does it work if you type it on one line with semicolon between? tarit bla ; case class bla

**Comment by bjornregnell** [comment]
also this will probably be affected by introducing the new Scala 3 enumerations. If you can fix it with making into one compilation unit by writing it on one line or put it inside 
``` 
object A:
  <seald stuff here>
```
then the exercise can be made consistent for now and we can then incorporate the enum stuff later and contrast it to sealed trait case obj etc...

**Comment by alfredgrip** [comment]
You can indeed solve this with a one line as follows:
```
sealed trait Färg; object Färg {val values = Vector(Spader, Hjärter, Ruter, Klöver)}; case object Spader extends Färg; case object Hjärter extends Färg; case object Ruter extends Färg; case object Klöver extends Färg
```
By entering this rather long one liner the rest of the task works as expected.

**Comment by bjornregnell** [comment]
yes but that is a loooong line; would it be nice to wrap the stuff in an object like: `object somegoodname:` to open multi-line editing i repl?

**Comment by bjornregnell** [comment]
BTW: it could perhaps be good to show your initial error in a new subtask as the error illustrate what sealed means... or what do you think?

**Comment by alfredgrip** [comment]
A possible solution would be:
```
object Färger:
  sealed trait Färg
  object Färg:
      val values = Vector(Spader, Hjärter, Ruter, Klöver)
  case object Spader extends Färg
  case object Hjärter extends Färg
  case object Ruter extends Färg
  case object Klöver extends Färg
```
and then
```
import Färger._
```
to acess members of the outmost object to continue with the rest of the task with ease.
If `Färger` is too similar to `Färg`, maybe `Kort` or `Kortlek` could be used instead.


> 
> 
> BTW: it could perhaps be good to show your initial error in a new subtask as the error illustrate what sealed means... or what do you think?

I think that could be useful. Even though it's mentioned in the instructions 

> En förseglad typ måste ha alla sina subtyper i en och samma kodfil.

it can be good to actually see the error

**Comment by bjornregnell** [comment]
Feel free to create what you think is the "best possible" solution :) Only downside of another subtask is that students dont want to many subtasks... but here it might be motivated. Also, we mighty to reconsider when Iäm ready with introducing enums. Or you can also think about where enum best fit. Probably in lab shuffle and therfore in corresponding exercise. But good to show both sealed trait case object and enum to contrast and compare. Think about it and then we can discuss when you have a finished solution. Ok?

**Comment by alfredgrip** [comment]
I thought about a solution to this and made some changes to my fork, please do check them out when you have time [here](https://github.com/alfredgrip/introprog/blob/master/compendium/modules/w06-patterns-exercise.tex).

I think that enums is a useful way of approaching the task we discussed earlier. However, I feel like it would make more sense to introduce students to enums later on in the course (w10 maybe?). Introducing enums just to solve one task would be in my opinion too confusing and unclear, and if you were to use enums in other tasks as well in w06 it would need a proper introduction in the slides. So it would be better to not do it in this task. 

I did however add a subtask where trying to extend a sealed trait in REPL with two seperate inputs, as I thought that would fit.

**Comment by alfredgrip** [comment]
Also, a few tasks in these exercises instructs the student to press tab twice while working in the `scala3-repl` while this doesn't work in the new repl. Are these tasks to be rewritten and modified or to be deleted? And is that something I should worry about or is it better if I leave that to you?

**Comment by bjornregnell** [comment]
Thanx!

It is easier to see what you have changed if you make a PR so please do. You can always make additional commits and push to your fork and the PR will include them until I merge. So please make a PR and I'll review it.

Also, if you can't find a good replacement, leave the non-functioning <TAB><TAB> experience for now and make a new issue about that as it probably span more than this exercise (?). We can discuss solutions in the new issue. If you leave stuff that MUST be fixed before printing add the latex `\TODO %comment on what to do` adjacent to the incomplete/non-working stuff and we will get a big bad red marker in the generated pdf as a reminder and also if relevant point to a corresponding issue on github by mentioning its #number. Ok?

I plan to introduce enums gradually with the simple enum cases such as `enum E { case A,B,C}` early on and then the basic ADT stuff later on. I haven't decided exactly yet where and how; this will impact several exercises.

**Comment by alfredgrip** [comment]
PR has been opened now!

**Comment by bjornregnell** [comment]
See https://github.com/lunduniversity/introprog/issues/546
