### ISSUE TITLE
Investigate solution to TAB+TAB not a feature in `scala3-repl`

### ISSUE THREAD

**Issue by alfredgrip** [lunduniversity/introprog#536]
Several exercises instructs students to press `TAB` twice while solving tasks in the REPL. This was a feature of the Scala 2 REPL, but not a feature of the `scala3-repl`. If this REPL is to be used in the course then these tasks need to be modified, rewritten or deleted. There are also slides that are affected of this.

Currently I've found the following that encounter this issue:

- w01 exercise expressions 6
- w06 chapter patterns 6.1.19
- w06 exercise patterns 3.b
- w06 exercise patterns 12.a

**Comment by bjornregnell** [comment]
Solution proposal:
In an early exercise, make a task that trains the student in using this for some method on an object in the standard lib:
* In Scala 3 one TAB shows completion possibilities and every next TAB takes you down the list
* If you want to see the the parameter types of the method, you can 1) call the method with empty argument list or 2) with some wrong arguments and the compiler will in a compilation error show what params are available, or (preferred) 3) with no args and the compiler will show the function type of the correspondning lambda if it takes any args or else it will just run the method if it is declared without a paramlist. Example:
```
scala> math.hypot()
1 |math.hypot()
  |^^^^^^^^^^^^
  |missing argument for parameter x of method hypot in package scala.math: (x: Double, y: Double): Double

scala> math.hypot
val res5: (Double, Double) => Double = Lambda$1617/0x0000000840791840@473c1e53

``` 
@alfredgrip What do you think about this? Which week should we show this in an exercise? I guess in w01, w02 or w03? I guess w02 or the first bullet in w02 and the second in w03?

**Comment by alfredgrip** [comment]
Sounds like a solid solution to this. Indeed, autocomplete could be useful so that could be introduced early in the course, w02 would fit well. The second bullet would, in my opinion, fit w03 better since the topic of that week is functions. So seeing the parameter types and the return type as with your example:
```
scala> math.hypot
val res5: (Double, Double) => Double = Lambda$1617/0x0000000840791840@473c1e53
```
could be useful when learning about functions.

**Comment by alfredgrip** [comment]
Just noticed that the power of `TAB` is already being introduced to students in w01 expressions exercise 6. So maybe w01 would fit better after all. However, that exercise also instructs the student to press `TAB` twice, which we know doesn't work in the `scala3-repl`. I will add the exercise to the bullet list above.

**Comment by bjornregnell** [comment]
Feel free to address this with PR:s for exercises in w01 #540 and w03 #542 if you like and if it is straight forward, or else discuss and handover to the ones assigned to it; @theolundqvist  @NiklasSanden

**Comment by theolundqvist** [comment]
I will take care of this in w01 exercise 06
