### ISSUE TITLE
Migrate exercise w05 classes to Scala 3

### ISSUE THREAD

**Issue by sadphi** [lunduniversity/introprog#538]
I am currently starting the migration of exercise w05. The migration seems to be pretty straightforward, although I am not sure how to approach the `new` keyword -- the keyword is now optional to use with regular classes, just like with case classes, however there still might be a benefit for students to learn how to use the keyword, thus the possibility of keeping it in some form in the exercise.

That said, this depends on if `new` will be taught in w05 or not, so I will skip `new` for now until a decision has been made.

**Comment by bjornregnell** [comment]
Yes good to use new explicitly, at leat at first. See also #539 that I just created. Feel free to propose a new (sub)task that exercise this new thing that seems to (currently) be called "universal apply methods" (previously in the evolution of Scala 3/"dotty" it was called "creator applications". We need a good Swedish translation. What do you think of "universella apply-metoder" eller "automatiska apply-metoder". The magic thing is that it also works for code from Java in Scala!
```
scala> val r = java.util.Random                                               
1 |val r = java.util.Random
  |        ^^^^^^^^^^^^^^^^
  |        Java defined class Random is not a value

scala> val r = java.util.Random()             // look no new                                  
val r: java.util.Random = java.util.Random@65e2cca9
```

**Comment by bjornregnell** [comment]
see also https://dotty.epfl.ch/docs/reference/other-new-features/creator-applications.html

**Comment by bjornregnell** [comment]
see also https://gitter.im/scala/contributors?at=60c753c5d161a54f0515494e

**Comment by bjornregnell** [comment]
Google translates "constructor proxies" to "konstruktörsfullmakter ", whis is pretty useless: 
https://translate.google.com/?sl=en&tl=sv&text=constructor%20proxies&op=translate

**Comment by bjornregnell** [comment]
I'm currently considering "proxy-konstruktion" and using the word "proxy" as a loan word (there are examples of this out there from e.g.babbla.se) or maybe just  "konstruktionsombud".

**Comment by sadphi** [comment]
I think "automatiska apply-metoder" describes it in a more understandable way than "universella", so I vote for "automatiska". 

As for constructor proxies, I think both words are fine, however "konstruktionsombud" seems more fitting as it doesn't sound as directly translated as "proxy-konstruktion", and is probably easier to understand for those that don't know what proxy means. But I don't really think it matters that much which one we choose here, as it mostly is a matter of taste. However I vote for "konstruktionsombud"
