### ISSUE TITLE
Introduce "new" as optional due to "universal apply methods" in lectures of week w05 on classes

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#539]
https://dotty.epfl.ch/docs/reference/other-new-features/creator-applications.html

Should we show which situations you actually need to use new? (want to directly refer to the constructor in your own apply)

We also need exercises for this.

**Comment by sadphi** [comment]
I can take a look at creating a new exercise when I'm done with migrating the existing tasks in #538.

**Comment by sadphi** [comment]
I just created a new task which should cover the use case of `new` in [this commit](https://github.com/sadphi/introprog/commit/e357c4861594b1c492a4b3e58e75af16abc17fe5). As for how universal apply methods are used, I've changed some instantiations in other tasks to not use `new` (see #548).
