### ISSUE TITLE
Migrate exercise w01 expressions to Scala 3

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#540]

**Comment by bjornregnell** [comment]
@theolundqvist

**Comment by bjornregnell** [comment]
See https://github.com/lunduniversity/introprog/issues/546

**Comment by theolundqvist** [comment]
@bjornregnell 

Changed scala-repl output. On mac the version is only given by typing `scala -version`.
Is this the correct output?

```
> scala
Welcome to Scala 3.0.0 (OpenJDK 64-Bit Server VM, Java 11.0.8).
Type in expressions for evaluation. Or try :help.

scala>
```

Issue #546 is now explained in w01 e06 but all mentions of double pressing TAB still needs to be removed.
