### ISSUE TITLE
Migrate exercise w02 programs to Scala 3

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#541]

**Comment by bjornregnell** [comment]
See https://github.com/lunduniversity/introprog/issues/546

**Comment by kuleshmaria** [comment]
Hi!
I'm working on migrating the exercises and I have a few questions:
- Should I prioritize using @main or leave/continue using an object with a main method, specifically in exercises 7, 9 and 11?
- In Exercise 4.b the student is asked to achieve the error message "Missing closing brace", but all the braces have been removed by using the new @main notation. Maybe we could replace it with something like this:
     4.b "Vad händer om du tar bort @main i koden ovan?" (and then for example try to run it as a script)
     4.c "Varför behövs @main-annoteringen?"
to discuss the role of @main in the program?

Minor thoughts:
- In Exercise 5 maybe it would be more fun to test mkString on a collection with length>1 to see the difference between xs.mkString and xs.mkString(",") ? For example by setting val ys =Array.fill(9)(0) and then call ys.mkString
- I was thinking about exercise 11 that maybe one could add some easier "warm-up" Java exercises (for example in exercise 8 where the student is asked to swap variables - to test the syntax for declaring and assigning values to variables) for students who have not coded in Java before

**Comment by bjornregnell** [comment]
* Yes prioritize @main, esp if the main-function takes no paraemters, typically:
```
@main
def run = ???
```
Or if you want to keep it on one line for space reasons:
```
@main run = ???
```
I show a primitve `def main(<usual boilerplate>` on lectures and I sometimes keep it esp if it is about looping through string-args, but you could also use the equivalent `@main def run(args: String*): Unit = ???`. If you give the params other built in types it will be checked at runtime and it could be good with an exercise showing such an exception.

* Braces are optional so we have two options and good to have seen both error due to missing brace and the new types of errors caused by bad indentation. The latter are perhaps easier to spot - missing parenthesis or curly braces are sometimes really hard bugs to fix as the compiler often has problems pinpointing where the actual omission is located... So you are welcome to extend the exercise with indentation problems and also keep some brace problem exercises. Point out that braces are optional and that you can mix styles in the same file if you think it helps readability. Sometimes braces are not optional, e.g. when you have multiple statements in the same one-parameter parameter list (such as in upprepa). 

Also: a new thing in Scala 3 is that you can have `(` instead of `{` in lambads such as 
```
xs.map( x =>
  bla
  bla
  bla
)
```
* Feel free to tweak the mkString exercise.
* As Java will be far less emphasized next round: All Java task should be moved to an appendix. You can add a `\TODO{move to java appendix}` on everything Java, until I get around to create that in the compendium file structure...

**Comment by kuleshmaria** [comment]
Thanks, I've fixed most of it now!
I'm now working on exercise 18, but I can't get :javap to work from the Scala 3 REPL.
I tried another option and I can create a file with
@main def plusxy(x: Int, y: Int) = x + y
compile it and run javap on the class-files in the terminal but it gives a different output.
What would be a good way to tackle this exercise?

**Comment by bjornregnell** [comment]
It would be good if you could adapt that task to using javap in terminal, if possible? 
I don't think we can expect that the Scala REPL developers will have gotten :javap to work in the Scala 3 REPL by print deadline.

**Comment by kuleshmaria** [comment]
I made a version using javap in terminal which seems to be similar and soon ready for a PR.

One more question, I noticed that exercise 16 uses the variable name "as" which is interpreted as a keyword and thus gets another font. Is there a preferred way to ignore it as a keyword in \code?

**Comment by bjornregnell** [comment]
OK good that javap in terminal works out similar.
The list of keywords in Scala 3 are here:
https://dotty.epfl.ch/docs/reference/syntax.html#keywords
As (pun intended :)) you can see here `as` is a so called "soft" keyword used in import renaming and we still can have variables etc called `as`. 
In several `.cls` files of this repo there are `lstdefinelanguage` that defines keywords and I have added the soft keywords there. See e.g. https://github.com/lunduniversity/introprog/blob/master/compendium/compendium.cls#L260
Even if it is allowed to have variables called `as` I think we should avoid them. Latex is not smart enough to know about this softness and I think it is valuable to have syntax highlighting on slides etc. Would it be meaningful to change the name `as` to something else in the exercises that clashes with the latex syntax highlighting settings?
Another solution is to, at specific places inside an exercise task make a local latex tweak with multiple lstdefines that first unset `as` and the reset it, but that's a hack...

**Comment by kuleshmaria** [comment]
Ah thanks, I was looking for the file with the definitions earlier
In the end I left the variable name as (no pun intended either) it is since it made sense based on the other variable names used throughout the course and made a little latex tweak.
