### ISSUE TITLE
make build.sbt work in Windows

### ISSUE THREAD

**Issue by alfredgrip** [lunduniversity/introprog#544]
Currently when one tries to build this repo locally using a computer running Windows OS it will fail.
This is due to the following line in `build.sbt`:
```
scala.sys.process.Process(Seq("tail", "-40", cmdOutputFile.getName), workDir).run
```
"Tail" is a Unix program and doesn't have native support for Windows. Running WSL on Windows does solve the problem, but true support for building this repo on Windows would be better.

**Comment by fritjof-b** [comment]
Is this the only line that hinders native support for Windows? If so, maybe we could add some logic that polls for the executing OS. From there, we could run some Unix or Windows program.

I'm not a Windows user myself, but what would be the equivalent program for Windows?

**Comment by bjornregnell** [comment]
Na, it seems easier to use xplatform java io to do what tail does

**Comment by bjornregnell** [comment]
I made it low priority as it is not critical to teaching preparations, but if anyone feels inclined to investigate and perhaps fix then its of course welcome.

**Comment by bjornregnell** [comment]
The fix needs testing on Windows.

**Comment by bjornregnell** [comment]
fixed by https://github.com/lunduniversity/introprog/commit/0b03eda66a2ad244dead207aafbffa5dd35793d7
