### ISSUE TITLE
make compendium more copy-paste-friendly from pdf files

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#549]
Problem: When you copy paste from compendium.pdf you loose white space when pasted in REPL. This is even more problematic with significant indentation in Scala 3.

Solution: Unknown as this 
https://tex.stackexchange.com/questions/195489/how-to-copy-paste-multiple-spaces-from-lstlistings
```
\lstset{
  basicstyle=\ttfamily,
  columns=fullflexible,
  literate={\ }{{\copyablespace}}1 {\ \ }{{\copyablespaceTwo}}1
}

\usepackage[space=true]{accsupp}
\newcommand{\copyablespace}{\BeginAccSupp{method=hex,unicode,ActualText=00A0}\ \EndAccSupp{}}
\newcommand{\copyablespaceTwo}{\BeginAccSupp{method=hex, unicode, ActualText=00A000A0}\ \ \EndAccSupp{}}
```
did not work in compendium.cls
gives this error
```
! Package inputenc Error: Unicode char �\lst@EC� (U+9EA5)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
```
Need to investigate why...

**Comment by bjornregnell** [comment]
It seems even worse for the proposed solution:
```
scala> def a =  ' '
1 |def a =  ' '
  |        ^
  |        illegal character '\u00a0'
```

**Comment by sadphi** [comment]
I've searched for other solutions as the solution from SO doesn't work, but I can't really find any other solutions to it. As mentioned in the same question on SO, it seems to be a limitation of the PDF spec.

**Comment by bjornregnell** [comment]
OK, this is a wont (be able to) fix. so sadly closing it is the only option....
