### ISSUE TITLE
W05 - Exercise - Task 11b)

### ISSUE THREAD

**Issue by Chokladmunk** [lunduniversity/introprog#55]
In the scala REPL for task 11b) line 5, it returns an error: 
```scala
<console>:13: error: type mismatch;
 found   : Unit
 required: Int => ?
       (1 to 100).foreach(print(rnd.nextInt(10)))
                               ^
```
When I changed the code to `(1 to 100).foreach(_ => print(rnd.nextInt(10) + ” “))` it worked but I'm not sure if that's the right way of writing it. What's the correct way?

**Comment by bjornregnell** [comment]
The signature of foreach requires a function and you need to give it  Int => Unit  (or some other types) but you gave it just Unit, hence the compile error.  You could write:
(1 to 100).foreach(i => print(rnd.nextInt(10) + " "))
And as the name i is not needed in the body of the function it is common in such situations to instead use the name _ to indicate that the name is not used. (You could also use gurka :))
I guess students will find i => ... simpler than _ => ... but you can use whatever as both are "correct"; they must learn both ways anyway and w05 is rather far into the course so they should cope...
