### ISSUE TITLE
New translations to Swedish needed regarding "universal apply methods"

### ISSUE THREAD

**Issue by sadphi** [lunduniversity/introprog#552]
New words have been introduced in Scala 3 that need to be translated to Swedish, and can be found [here](https://dotty.epfl.ch/docs/reference/other-new-features/creator-applications.html). Some initial translations were proposed in #538, of which I think Universal apply methods -> "automatiska apply-metoder" and Constructor proxies -> "konstruktorombud" are good starting points.

**Comment by bjornregnell** [comment]
OK lets go with those: "automatiska apply-metoder" and "konstruktorombud" (alt. konstruktion via ombud el. konstruktion via egen fabriksmetod el. konstruktion via egen apply-metod)
