### ISSUE TITLE
Example issue with rollover

### ISSUE THREAD

**Issue by M0R60TH** [lunduniversity/introprog#592]
Several pieces of code used in the examples for week to have a slight issue when run through sbt. The use of print instead of println is creates rollover between smileys and the sbt output that are confusing to read in the terminal. Println is already used for some of the smileys.

![image](https://user-images.githubusercontent.com/55506884/133340213-666596e2-ac86-4a00-b730-c3b6b4782fab.png)

Should this be changed (or is is to minor an issue and I'm just being pedantic?)

**Comment by Husenap** [comment]
I think that it's a pretty minor issue, but it's still good to have consistency in the example code.

Using println and print in this snippet doesn't make much sense
```scala
if highscore then println(":)") else print(":(")
```

So I don't see why it shouldn't be changed, go for it 🚀

**Comment by fritjof-b** [comment]
It might let the person writing and running the code reflect on the difference between `println` and `print`. If you're used to programming I guess it is more clear, but maybe not for the eyes of a new programmer. At least for me it wasn't all that clear in the beginning that small differences could have large effects.

**Comment by bjornregnell** [comment]
fixed by #591
