### ISSUE TITLE
Update compendium with Scala3's automatic eta-expansion (critical when f _ syntax gets deprectaed)

### ISSUE THREAD

**Issue by Husenap** [lunduniversity/introprog#604]
The automatic eta-expansion rules have been updated in scala 3.

```scala
val f = fun _          // old syntax has been deprecated
val f = () => fun()    // this is now the recommended way
```
See [AUTOMATIC ETA EXPANSION - MORE DETAILS](https://docs.scala-lang.org/scala3/reference/changed-features/eta-expansion-spec.html#rules)
and [AUTOMATIC ETA EXPANSION](https://docs.scala-lang.org/scala3/reference/changed-features/eta-expansion.html#automatic-eta-expansion-and-nullary-methods)
### To do
- [ ] Investigate the amount of work it will take to update the compendium
- [ ] Introduce the concept of a thunk when teaching about functions
- [ ] Update code examples to get rid of the old deprecated syntax
- [ ] Update the slides that explain how to do it in the old way

**Comment by bjornregnell** [comment]
https://en.wikipedia.org/wiki/Thunk

**Comment by bjornregnell** [comment]
https://docs.scala-lang.org/scala3/reference/changed-features/eta-expansion.html
It says "is going to be deprecated" but it is not deprecated yet so it is not a very big hurry...

**Comment by bjornregnell** [comment]
Thunk is part of lect w03 and it seems as if all eta expansion underscore usages have been washed out by now...
