### ISSUE TITLE
Radbrytning saknas sida 196 (Compendiumet)

### ISSUE THREAD

**Issue by JoPoLu** [lunduniversity/introprog#605]
Se _figur 1_: [https://cdn.discordapp.com/attachments/887647183841673227/892750637555654696/Screenshot_from_2021-09-29_14-28-28.png]() (_figur 1_)

**Comment by bjornregnell** [comment]
fixed by https://github.com/lunduniversity/introprog/commit/25fb0c52e23fd29ca2afbe4b7b28b6b69a446511

**Comment by bjornregnell** [comment]
@JoPoLu Thanks for finding this issue! Next time would be good to use english as we have international contributors also to this repo. Also you can attach small files directly here on github so you dont need to reference outer space :)
Thanks again!
