### ISSUE TITLE
Ambiguity in Fisher-Yates pseudocode in lab w07_shuffle

### ISSUE THREAD

**Issue by snctfd** [lunduniversity/introprog#609]
The pseudocode for the Fisher-Yates shuffle algorithm as written in the compendium specifies the following: `r <- slumptal mellan 0 och i`. This has led to several students being confused about why their implementations don't give an even shuffle, because they interpreted the range as 0 <= `r` < `i`. I would argue that `r <- slumptal så att 0 <= r <= i` would be a more clear and precise formulation of the sentence.

There is of course some learning value in debugging why their algorithm doesn't work properly and checking their assumptions, but I would argue that ambiguously defined pseudocode provides more frustration than it does opportunity for learning.

**Comment by bjornregnell** [comment]
Yes, that's an option @fritjof-b 
@snctfd What do you think about linking to the relevant section on wikipedia and say that they need to think carefully about the interval or something?
