### ISSUE TITLE
Incorrect folder structure in workspace/w13_photo

### ISSUE THREAD

**Issue by julius-andreasson** [lunduniversity/introprog#619]
The folders structure in 'workspace/w13_photo' is incorrect, and results in SBT being unable to find the source code.

The source code is located in 'w13_photo/src/', when it should be located in 'w13_photo/src/main/scala/'. 

Proposed fix: Update folder structure. I did it in a public fork, but I don't have authority to merge with this repo.

**Comment by Husenap** [comment]
You can create a Pull Request from your fork to this repository with the suggested changes.

**Comment by bjornregnell** [comment]
Thanks! PR welcome! (or let me know if you want me to fix it myself @julius-andreasson )

**Comment by julius-andreasson** [comment]
Thank you for the advice. Double-checked and made a PR!
