### ISSUE TITLE
make sure the copy method of case classes is included in lectures

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#627]
it seems as if the copy method is not so easy to find among the lecture slides... maybe it's even missing...

**Comment by sadphi** [comment]
I've taken a look at both W05 Classes in the compendium, and at the W05 lecture slides, but as far as I can see, I can't find any mention of copy at all. The first mention I find is in W07 Sequences, at section `7.1.45 Exempel: Polygon som oföränderlig case class`.
