### ISSUE TITLE
Scary warnings pop up when kojo is run from the terminal using scala-cli and from the vscode output log. 

### ISSUE THREAD

**Issue by pontussjostedt** [lunduniversity/introprog#637]
C:\Users\Pontu\Scala\w01-kojo>mkdir kojo

C:\Users\Pontu\Scala\w01-kojo>cd kojo

C:\Users\Pontu\Scala\w01-kojo\kojo>code .

C:\Users\Pontu\Scala\w01-kojo\kojo>curl -o kojolib.scala -sL https://cs.lth.se/pgk/kojolib

C:\Users\Pontu\Scala\w01-kojo\kojo>code .

C:\Users\Pontu\Scala\w01-kojo\kojo>scala-cli run .
Compiling project (Scala 3.1.2, JVM)
Warning: Flag -bootclasspath set repeatedly            <- Spooky warning
Warning: Flag -classpath set repeatedly                  <- Spooky warning
Compiled project (Scala 3.1.2, JVM)

**Comment by bjornregnell** [comment]
For the record: here is the OUTPUT tab screen dump in vs code by @pontussjostedt 
![image](https://user-images.githubusercontent.com/3601817/177136914-e4c4d21b-0a3a-4bb3-9b0f-28a05e8e647d.png)

**Comment by bjornregnell** [comment]
I think the OUTPUT tab normally has a lot of logging messages, compare forinstance to all the gibberish that the vscode latex plugin produces here. So I'm not sure we should bother students with this as I normally think students either has the TERMINAL or DEBUG CONSOLE tab open or not the bottom pane open at all (toggeled with Ctrl+J). SO an explanation of the log might be more confusing than helpful. What do you think?

**Comment by bjornregnell** [comment]
Do you think its ok to leave the OUTPUT tab's logging "spam" without comment in the compendium?

**Comment by pontussjostedt** [comment]
For me the output popped up when running the program from cmd as described in Appendix A. I think that it would be easier to read the appendix if there was no disclaimer(like it is now) and if there was to be a lot of questions you could always add it in later( overlooking the fact that there will be several printed versions in circulation). One possibility could be to just add a small comment inside kojolib.scala which people will see when they write the code without cluttering the appendix.

**Comment by bjornregnell** [comment]
OK, I'll close this for now and we will see if this turns out to be a problem and I'll mitigate during lectures.
