### ISSUE TITLE
fix problem with curl certificate+redirect from course web typo3 link; error on new version of curl

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#642]
Better use another link but still short to avoid curl problem. How to best make nice short URL if we can't get https://cs.lth.se/pgk/kojolib/
 working with curl?

Message from @andrephilipsson (copy-paster from our Discord server):

Funkar inte:
```
curl -o kojolib.scala -sL https://cs.lth.se/pgk/kojolib/
```

När jag kör följande (notera extra -S för att visa felmeddelande):
```
curl -o kojolib.scala -sSL https://cs.lth.se/pgk/kojolib/
```

Får jag följande felmeddelande:
```
curl: (60) SSL certificate problem: out of memory
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Detta funkar:
```
curl -o kojolib.scala -sL https://raw.githubusercontent.com/lunduniversity/introprog/master/workspace/w01_kojo/kojo.scala
```

**Comment by andrephilipsson** [comment]
> To be tested if it works? `curl --insecure -o kojolib.scala -sL https://cs.lth.se/pgk/kojolib/`

Can confirm that this works as expected on an M1 Mac

**Comment by bjornregnell** [comment]
I have now created a rather short URL that does not redirect. Could you check if this works on Apple: @andrephilipsson
```
curl -o kojolib.scala -sL https://fileadmin.cs.lth.se/kojolib.scala
```

**Comment by bjornregnell** [comment]
Great! Should be fixed now by https://github.com/lunduniversity/introprog/commit/02e429224c917a96ad3d6b8b29383e97f2f6d511
