### ISSUE TITLE
Improve readability in "verktyg" page

### ISSUE THREAD

**Issue by oliverlevay** [lunduniversity/introprog#654]
[https://cs.lth.se/pgk/verktyg/](https://cs.lth.se/pgk/verktyg/)

Right now the instructions are unclear and students with a windows machine for example has to filter out a lot of information about mac / linux and figure out what to keep and not to keep. Suggestion is to make the instructions more divided, and I would personally like a numbered list.

1. Install Java
2. Install Scala
3. Install vscode
4. blablabla

**Comment by bjornregnell** [comment]
Update live now at https://cs.lth.se/pgk/verktyg/
What Do You Think @oliverlevay

**Comment by theolundqvist** [comment]
Kan man kanske lägga en toc under rubriken verktyg i navigationsmenyn på vänster så som det ligger en om man klickar på "schema" 
<img width="236" alt="image" src="https://github.com/lunduniversity/introprog/assets/31588188/d066022c-fd66-46a8-83cb-b3f01193cb68">
Förslagsvis med samma rubriker som redan ligger i texten.
Windows
linux
mac
editor
kojo

**Comment by theolundqvist** [comment]
Hörde med studenterna i salen och de tyckte att det var lite klurigt att installera allt man behövde men att det gick bra i och med guiden på kurshemsidan eller att det gick bra i och med hjälpen man fick. (Installationskvällar/handledare osv)

**Comment by bjornregnell** [comment]
Bra idé! Vi tar det inför nästa år - då har även kanske det klarnat hur övergången från typo3 till drupal ska gå till och om drupal kommer tillåta att jag med javascript suger in html-kod på sidorna. Om inte så kommer jag flytta vissa sidor till readme.md-liknande filer på github eftersom det är för svårt att uppdatera med musarmsriskerande gui på ännu ett ställe...

**Comment by bjornregnell** [comment]
Att ha sidomenyer får inte i typo3 med javascript-hacket och oklart när drupal påtvingas oss. Jag stänger denna nu eftersom läsbarheten av verktygssidan är klar med en rubrik per os etc.
