### ISSUE TITLE
Scala 2 differs from 3 with forward declarations

### ISSUE THREAD

**Issue by marcusklang** [lunduniversity/introprog#662]
```scala
{
   val b = a;
   val a = 42;
}
```
Compiles and works, but in Scala 2 you were given a warning. In Scala 3 you are not given a warning.

b is given the value 0.

Update compendium answers for exercise 4.2 to reflect changes.

**Comment by bjornregnell** [comment]
https://docs.scala-lang.org/scala3/reference/other-new-features/safe-initialization.html

**Comment by bjornregnell** [comment]
https://github.com/lampepfl/dotty/issues/16083
