### ISSUE TITLE
Consistent language regarding "Uniform Access/Enhetlig Access"

### ISSUE THREAD

**Issue by EdvinGroth** [lunduniversity/introprog#663]
In the compendium under 4.2.1 in the first question it asks you to connect the concept "Uniform Access"(number 14) to a description but in the rest of the compendium it is always referred to as "Enhetlig Access". The rest of concepts are in swedish except for this one, if this is not intended i would recommend changing the question and the answer sheet to "Enhetlig Access" instead of "Uniform Access".

**Comment by bjornregnell** [comment]
Good catch! I aggree. It could even be "enghetlig acces (eng. uniform access)" to connect the terms. Do you want to make a PR yourself or do you want me to fix this?

**Comment by bjornregnell** [comment]
If you run into troubles when fixing PR just ask a tutor in classroom when time permits.

**Comment by bjornregnell** [comment]
fixed by #664
