### ISSUE TITLE
 (4.2.1) - Quiz w04 - Task 1

### ISSUE THREAD

**Issue by valterbergstrand** [lunduniversity/introprog#665]
Type alias is mentioned in Task 1, but the terminology is not explained during the chapter. Maybe add a short description. Something similar to:

"Nyckelordet type används för att skapa en referering till en annan datatyp. Kan användas för att skapa en förkortning av en datatyp med annars längre syntax, som exempelvis när man specificerar vilken elementen i en Array ska ha: 'Array[Char]'"

scala> type Bokstäver = Array[Char]
// definerar Bokstäver som en type alias till Array[Char]

scala> val Ord: Bokstäver = Array('a', 'b', 'c')
val Ord: Bokstäver = Array(a, b, c)

**Comment by bjornregnell** [comment]
Yes, good catch! Yes there should be a slide on type aliases in week 4.

**Comment by bjornregnell** [comment]
I will move the slide from week 7 on type aliases to week 4.

**Comment by bjornregnell** [comment]
![Screenshot from 2022-09-21 12-50-36](https://user-images.githubusercontent.com/3601817/191487374-5819436c-64c7-4756-9bc3-fb360d60f0c7.png)
