### ISSUE TITLE
w04-objects-exercise.tex

### ISSUE THREAD

**Issue by valterbergstrand** [lunduniversity/introprog#666]
At line 88 and 89, should it not be:
import Underjorden.Mullvaden.*
import Underjorden.Masken.*

since Mullvaden and Masken are members of Underjorden (identation at line 71 and 75)

**Comment by valterbergstrand** [comment]
No, I made a misstake by not pasting filecode into REPL correctly

**Comment by snctfd** [comment]
@valterbergstrand feel free to re-close (assuming reopen was accidental) or add more context :)

**Comment by valterbergstrand** [comment]
Yes it was :)
