### ISSUE TITLE
The introprog jarfile has two different names in problem 7 chapter 4

### ISSUE THREAD

**Issue by pontussjostedt** [lunduniversity/introprog#669]
So far this has caused a lot of people whom do not read carefully to get stuck and I therefor suggest that there should be different file names for the same file juggled around.

**Comment by bjornregnell** [comment]
@pontussjostedt Is the fix above solving the issue?

**Comment by pontussjostedt** [comment]
Ja, nu när det explicit står att du ska anpassa efter namnet borde det ju bli mindre problem.
