### ISSUE TITLE
4.1.43 - clarify syntax for adding classpath in Windows

### ISSUE THREAD

**Issue by valterbergstrand** [lunduniversity/introprog#670]
Instead of writing
(Windows: semikolon)
write
(i Windows skiljs sökvägar med semikolon istället för kolon i Linux eller andra operativsystem)
since the (Windows: semikolon) can be interpreted as relating to the syntax (with the use of ":" in the sentence), which could be confusing.

**Comment by bjornregnell** [comment]
Thanks! I will fix this in my next commit.
