### ISSUE TITLE
4.3 Task 6 - for-loop is written with Scala 2 syntax

### ISSUE THREAD

**Issue by valterbergstrand** [lunduniversity/introprog#671]
in 4.3, Task 6a is written with Scala 2 syntax, maybe change to Scala 3 syntax for consistency?

**Comment by bjornregnell** [comment]
Yes the `for` should have a `do`. 
Do you want to contribute with a PR yourself or do you want me to fix it?

**Comment by bjornregnell** [comment]
I guess the whole lab should be washed out of curly braces and primitive mains as well (even if curly braces never will be deprecated and is perfectly valid Scala 3 syntax...). What do you think?

(But old-style for, while, if without do or then will be deprecated at some point if I have understood it correctly)

**Comment by bjornregnell** [comment]
There is also i while missing a do in task 7 and an if missing a then in task 11.
