### ISSUE TITLE
Consider making scala-cli or sbt mandatory in blockmole

### ISSUE THREAD

**Issue by OlofBen** [lunduniversity/introprog#677]
Since the instructions on how scala-cli and sbt works are in this week's theory, there should in my opinion be some requirement in the lab that makes sure that the students use one of the two in at least part of the lab (blockmole, w04).

**Comment by bjornregnell** [comment]
related to #672

**Comment by bjornregnell** [comment]
scala-cli is now the tool of choice in blockmole, as seen in latest version of workspace
