### ISSUE TITLE
[w05-blockbattle] Add requirement that code outside of BlockWindow should use block coordinates

### ISSUE THREAD

**Issue by snctfd** [lunduniversity/introprog#688]
It seems that a small subset of students are making the BlockBattle lab harder for themselves than it has to be by using pixel coordinates everywhere. Currently, this does not conflict with any of the requirements, but produces code that is extremely messy. Perhaps a requirement should be added that the code outside of BlockWindow should use block coordinates, in order to help guide students into making the right design choices?

**Comment by bjornregnell** [comment]
Seems like a very good idea for next year! PR welcome when you get some spare time.
