### ISSUE TITLE
Importing projects into Eclipse

### ISSUE THREAD

**Issue by majstenmark** [lunduniversity/introprog#69]
See appendix on Eclipse ScalaIDE on importing code. Then a .classpath file has to exist to specify Scala-jre otherwise Eclipse will not recognize the project as a Scala project. Otherwise the user has to first create a project and then import the code. @bjornregnell: Change appendix to whatever method will be used during the lectures.

**Comment by bjornregnell** [comment]
The sbt eclipse plugin generates .classpath etc. Let's test this eventually and the I update appendix accordingly.
