### ISSUE TITLE
[w07] Include explicit definition of "iteration" in chapter

### ISSUE THREAD

**Issue by valterbergstrand** [lunduniversity/introprog#693]
In my opinion, the term "iteration" is quite useful in discussion and explanation of subjects pertaining to sequences. The term is used in the chapter at different points, but I couldn't find an explicit definition, so maybe a explicit definition should be added?

**Comment by bjornregnell** [comment]
![image](https://user-images.githubusercontent.com/3601817/195562778-f4c7cde3-c87f-47dc-a444-dfe7f2b7cb8b.png)

**Comment by bjornregnell** [comment]
![image](https://user-images.githubusercontent.com/3601817/195563638-25def806-1587-4a9a-9036-9a6eb13b42a9.png)

**Comment by bjornregnell** [comment]
fixed by 120480e695586fabd379e3b524efbfcc52bff6ba
