### ISSUE TITLE
[w07] Task 23, usage of different term than "traversering"

### ISSUE THREAD

**Issue by valterbergstrand** [lunduniversity/introprog#694]
In my opinion, the usage of "traversering" in the task 23 is difficult to interpret in the context of programming. I would maybe use "iteration" with some kind of prepostion, something along the liens of the phrase "iteration av". For example:

"Implementation ovan kan innebära traversering av alla tecken i strängen två gånger och behöver minnesutrymme för dubbla antalet tecken. Varför"?

to

"Implementation ovan kan innebära att iterationen av tecknena i strängen sker två gånger, och behöver minnesutrymme för dubbla antalet tecken. Varför?"

**Comment by bjornregnell** [comment]
Thanks! I can fix this - I think the sentence could be rewritten a bit more to use "gå igenom" insted of "iterationen" but I'll think a bit more about that.

**Comment by bjornregnell** [comment]
fixed in ceb75729ba70f4458d92a71b8aeac5d91c19a32e
