### ISSUE TITLE
Quickref - add refrence to scala.util.Random

### ISSUE THREAD

**Issue by valterbergstrand** [lunduniversity/introprog#698]
I could not find an declaration and description of scala.util.Random in the quickref. This is something I think should be included, but I don't know where it should be placed.

**Comment by valterbergstrand** [comment]
more specifically, the method scala.util.Random.nextInt

**Comment by bjornregnell** [comment]
Thanks for the issue.

It is actually part of the Java JDK and just delegated from scala.util.Random to java.util.Random but that is not easy to know if you are not used to look into the Java part of the quickref. 

I guess next year we should restructure the whole quickref to have more Scala and less Java and just focus the Java part on JDK stuff that is interesting to use from Scala. What do you think @valterbergstrand ?

In any case util.Random should be in the Scala part....
