### ISSUE TITLE
Project tasks chapter 12, does tabular exist?

### ISSUE THREAD

**Issue by JonatanKrakhede** [lunduniversity/introprog#711]
On 12.1.2, it says that one can choose bank, tabular, music, photo or a self-defined project. Bank, music and photo all have their very own pages where it says what one should do and what functions one can use, but not for tabular. There is nothing that explains what one should do with tabular, should it be like that and why?

**Comment by bjornregnell** [comment]
This is a left-over from last year that should have been removed, this a bug. Now fixed by https://github.com/lunduniversity/introprog/commit/5e27c3a99a9c947dfbf276f462b47602ab37192c
