### ISSUE TITLE
Appendex E, Documentation E.2.2, guidelines nonexistent?

### ISSUE THREAD

**Issue by JonatanKrakhede** [lunduniversity/introprog#715]
In E.2.2 below the box with comments:
"Dokumentationskommentaren slutar med */ rakt under asterisk-kolumnen.
I figur ?? på sidan ?? visas exempel på dokumentationskommentarer. Annoteringen
@param i början på en rad ger en speciell kommentar angående parametrar. Annotering-
en @return i början av en rad ger en speciell kommentar angående vad som returneras vid
metodanrop.
_Riktlinjer för hur du skriver dokumentationskommentarer:_"
And the guidelines are not there? Why? Should there be guidelines and if not, why does it say that there should?

**Comment by bjornregnell** [comment]
It's good practice to check existing issues (also closed) and search for similar issues. Anyway thanks for reporting. Closing this as already fixed as reported in #714.

**Comment by JonatanKrakhede** [comment]
Aight sowy
