### ISSUE TITLE
unimportant misspelling

### ISSUE THREAD

**Issue by isakstorme** [lunduniversity/introprog#717]
"litteral" and "literal" used inconsistently i believe

**Comment by bjornregnell** [comment]
thanks for spotting this. Do you have any positional refs? (Or else a search will do when fixing this.)

**Comment by bjornregnell** [comment]
In Swedish it should be with two t:s: https://sv.wiktionary.org/wiki/litteral

In English it should be with one t: https://en.wiktionary.org/wiki/literal

**Comment by isakstorme** [comment]
Pages 26, 28, 38, 46, 49, 95 and 96 I think.
