### ISSUE TITLE
Improvements for muntabot

### ISSUE THREAD

**Issue by elsaogestad** [lunduniversity/introprog#719]
During the lunch meeting we discussed how students could practice for the oral exam. I had an idea that we should encourage people to do a “test oral exam”, where one is asking the questions and the other one is answering. From personal experience when I trained for an oral exam, it helped me a lot because I realized what I needed to train more on.
We later discussed that it could be added as an exercise task for next year's course offering.

**Comment by bjornregnell** [comment]
fixed in https://github.com/lunduniversity/introprog/commit/1511e72ef964c5ecef13b2d9c3d6cf8e82480966
