### ISSUE TITLE
typo (?) in readme for `workspace/w04_blockmole`

### ISSUE THREAD

**Issue by fritjof-b** [lunduniversity/introprog#720]
README for week4 lab blockmole provides the following steps:

>
>Kör i linuxterminal med detta kommando:
>
>   `scala -cp "introprog.jar:." Main`
>
> Om du kör i Windows Powershell eller Cmd byt kolon mot semikolon i kommandona ovan.

But should probably be `scala -cp "introprog.jar:." run`, since we're using 

```scala
// hello-window.scala

@main
def run(): Unit =
...
```

At least the former doesn't work for me, but the latter does. :-)

Submitting a PR for this, feel free to reject if not applicable.

**Comment by bjornregnell** [comment]
Are you perhaps using the new experimental runner for scala-cli that replaces the old `scala` with then new scala-cli runner?
https://scala-cli.virtuslab.org/docs/reference/scala-command/

**Comment by bjornregnell** [comment]
Aha - never mind my previous comment. I see what you mean. (All this have to be fixed when the new runner is released...)

**Comment by fritjof-b** [comment]
Great, had to make sure I wasn't fooling anyone. 👍 

At least one done, happy new year for now!
