### ISSUE TITLE
Add scala version on the releases, so it is clear if scala 2 or 3 were used for that version

### ISSUE THREAD

**Issue by OliverPerssonB** [lunduniversity/introprog#726]
It is nice to know quickly which version was used for which release. The support for scala 3 is not as common as scala 2. Many new features (such as enums) are not available in scala 2.

**Comment by bjornregnell** [comment]
Good idea! Thanks.

**Comment by bjornregnell** [comment]
We will use Scala 3 from now on. There will be an LTS scheme for Scala releases and 3.3 will be the first Scala LTS and we will probably follow LTS versions. Anyway, I will include the Scala version in the release information of which major Scala versions we are using from now on.
