### ISSUE TITLE
improve quickref

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#739]
* Make the java-part more focused on the JDK.
* Reduce the number of pages in the java part
* Include more Scala 3 constructs, like extension, given-using, etc.
* make a summary of syntax for common constructs (the first page is very cramped, use the space released by reduced space for java to make more room for syntax constructs and examples)
* include scala-cli commands
* include scala toolkit examples
* include parts of introprog-scalalib

**Comment by bjornregnell** [comment]
see also #418 and #736

**Comment by bjornregnell** [comment]
consider add info about scala toolkit also in appendex C or F and on slides, exercises etc

**Comment by bjornregnell** [comment]
if java-part is revamped and not connected to retired contributors, consider moving quickref to its own repo, perhaps under bjornregnell

**Comment by bjornregnell** [comment]
consider moving quickref to Scala-source from which latex and markdown can be generated; this may be valuable if quickref is to be contributed to scala-lang, which is based on markdown

**Comment by bjornregnell** [comment]
add info on ScalaJS and Scala Native. Add a short part on javascript as a runtime, alongside Java/JVM/JDK -> three subparts on each runtime?

**Comment by EliasAAradsson** [comment]
I believe too that it would be a good idea to separate the Scala and Java quickrefs. However, I don't believe all of this to be necessary:

    * Make the java-part more focused on the JDK.
    * Reduce the number of pages in the java part
    * Include more Scala 3 constructs, like extension, given-using, etc.
    * make a summary of syntax for common constructs (the first page is very cramped, use the space released by reduced space for java to make more room for syntax constructs and examples)
    * include scala-cli commands
    * include scala toolkit examples
    * include parts of introprog-scalalib
  
The way I see it, the primary function of the quickref is to be a substitute for proper documentation of Scala and it's standard library, to be use when access to proper documentation is limited or unnecessary, first and foremost in a pen and paper exam situation.
