### ISSUE TITLE
Misplaced control question about side effect.

### ISSUE THREAD

**Issue by OlofBen** [lunduniversity/introprog#746]
In the first lab there is a question about side effects (section 1.3.2 question 9), but the information is in the next chapter.
The question needs to be moved or removed.

**Comment by OlofBen** [comment]
The question is hard to move since the next lab (w3) does not have any control questions. So it might just be best to remove it.

**Comment by bjornregnell** [comment]
OK let's remove it. Do you want to come with a PR on that or do you want me to do it?
