### ISSUE TITLE
Change Instruction and wording in exercise 2.4 a)

### ISSUE THREAD

**Issue by axelnilsson98** [lunduniversity/introprog#749]
The wording and instructions in exercise 2.4 might be misleading to a person who is not used to how linux and compilation works. 

The exercise is about compiling a .scala file and looking for the files created by the compiler.

The command for looking for this files in the compendium is:
ls .scala-build/project*/classes/main 

This command doesnt always work when there are multiple project* folders (the problem has been seen on at least 2 mac os computers)

I think the problem stems from students not realizing what the command is doing and what the '*' means. Is it better to change the text to something like:
"look at the files that are in the folder starting with project in the folder .scala-build ...."

instead of giving them a "magical" command that they dont understand?

**Comment by bjornregnell** [comment]
good point!
PR welcome!

**Comment by bjornregnell** [comment]
We should then state that the should look for files with names ending with .class  in some subfolder with a name starting with project...
(I think the command works but it lists multiple dirs, but the confusion might still be there)
Would you like to make a PR yourself or do you want me to do this?

**Comment by axelnilsson98** [comment]
pr has now been sent. What do you think of the wording?
