### ISSUE TITLE
re-prioritize control questions at end of lab blockmole

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#752]
there is quite some focus on nitty-gritty details such as classpath, jar-files etc in control questions at the end of lab blockmole; perhaps better to invent some new more important ones and remove some of the nitty-gritty-ones? Suggestions in this comment thread welcome!

Currently in file w04-objects-lab.tex:
```
\begin{enumerate}[noitemsep]
\item Till vad används \emph{classpath}?
\item Vad är en \code{jar}-fil?
\item Vad innebär punktnotation?
\item Ge exempel på användning av \code{import} och förklara vad som händer.
\item Vad är fördelen med skuggning och lokala namn?
\item Vi använde flera singelobjekt som olika s.k. \code{moduler} i denna laboration. Vad är fördelen med att att dela upp koden i moduler?
\item Gå igenom målen med laborationen och kontrollera så du har uppfyllt dem.
\end{enumerate}
```

**Comment by OlofBen** [comment]
How does the mole's coordinates change when the mole is moving from upwards?

This covers how coordinates work in a window, but might be too easy since the students have done this in 7.c

**Comment by bjornregnell** [comment]
fixed by https://github.com/lunduniversity/introprog/commit/8154e84c47b02ddb093e5f4ec49c0361c34d80f4
