### ISSUE TITLE
Misleading tip in 4.2 Objects question 7a

### ISSUE THREAD

**Issue by lego-eden** [lunduniversity/introprog#754]
In 4.2 Objects question 7a, the tip says to look into the introprog docs [(docs)](http://cs.lth.se/pgk/api/) in the PixelWindow class to find out what the default arguments are when you create one. However there are no default arguments shown in the documentation.

My suggestion for this if to change the tip to hint at looking in the code [(pixelwindow class)](https://github.com/lunduniversity/introprog-scalalib/blob/master/src/main/scala/introprog/PixelWindow.scala#L108) for info about the default arguments, or alternatively updating the docs to show the default arguments.

I will probably not submit a pull request myself.

**Comment by bjornregnell** [comment]
Thanks for reporting. I'll make a PR eventually. Perhaps we should check if the later version of scaladoc generates documentation that shows default arguments in doc so that there is no need to investigate the default values in the code.

**Comment by bjornregnell** [comment]
Is the new scaladoc in its lates version capable of rendering default arguments? Investigations needed. And a new api doc for introprog-scalalib should be generated.
