### ISSUE TITLE
Divide task 5 and 5(a, b, c) in words lab into two distinct tasks to avoid missing / skipping a, b, c

### ISSUE THREAD

**Issue by RurikHagman** [lunduniversity/introprog#775]
Some students are missing or skipping the tasks:

a) Vilka ord brukar följa efter han respektive hon i Stevensons ”Skattkammarön”?
b) Vilka ord brukar följa efter han respektive hon i Stringbergs ”Inferno”?
c) Vilka ord brukar följa efter he respektive she i Austens ”Pride and Prejudice”?

in the words lab. Some have a hard time coming up with the solution on the spot when asked about it. 
It might be a good idea to seperate these tasks from task 5 into their own to avoid confusion.

**Comment by Husenap** [comment]
An alternative would be to include output from the followFreq in the test program.

**Comment by bjornregnell** [comment]
fixed by https://github.com/lunduniversity/introprog/commit/dbf796288dcd1c08fd3c60b15651f7089b335281
