### ISSUE TITLE
W9-Words is not very interactive. 

### ISSUE THREAD

**Issue by OlofBen** [lunduniversity/introprog#776]
Most, if not all, other labs got some kind of graphical interface where students can interact with the program they just created. However words lack such an interface and just prints some facts about a book when the lab is finished. This is not exciting enough for most students, so they complete the lab as quickly as possible just to move on.
 
The lab does not become fun (in my opinion) until you complete task 8 and 9. These tasks make it so the program writes its own messages. 

Perhaps the lab can be restructured by removing task 6, but making task 7, 8, 9 mandatory?

**Comment by bjornregnell** [comment]
I will keep it as is, as course evaluation indicate that the lab is already demanding for some students and most students find it "lagom svår". Not all labs need to be interactive and there is a point in having some of the more fun stuff in extra tasks for some labs.
