### ISSUE TITLE
Add gitignore to Snake lab

### ISSUE THREAD

**Issue by OlofBen** [lunduniversity/introprog#779]
There were some groups who had problems with git in the Snake lab, because they pushed compiled files and got into some nasty mergeconflict.  This can be solved by either having a gitignore file in the workspace or by adding an example of a gitignore to the compendium.

**Comment by OlofBen** [comment]
In my opinion, it would be better to add it to the compendium. This makes it seem less like magic, and the student will learn how to avoid these issues in the future.

**Comment by pontussjostedt** [comment]
I second this, I spent a considerable amount of time helping people cleaning up their repos today.

**Comment by bjornregnell** [comment]
There is a .gitignore in the workspace here:

I guess you mean copying that to the snake dir?

Fixed here: https://github.com/lunduniversity/introprog/commit/4894c26e2f3c51e7c6b5cd512b2a6aec698fcc74

And here: https://github.com/lunduniversity/introprog/commit/ad306bc09094da9d79398a595f03b0ee1e68ab7c
