### ISSUE TITLE
Add predicates for Option and Try to quickref, and rewrite the entire section regarding Option, Some, None, and Try, Success, Failure

### ISSUE THREAD

**Issue by EliasAAradsson** [lunduniversity/introprog#788]
Rewriting is necessary since there's currently no space for additions. It's also my belief that rewriting this section can improve usefulness in other ways.

**Comment by EliasAAradsson** [comment]
I would like to assign this issue to myself and add the label `quickref`, but it doesn't seem as though I have this permission.

**Comment by bjornregnell** [comment]
> I would like to assign this issue to myself and add the label `quickref`, but it doesn't seem as though I have this permission.

Assigned you and label now.

**Comment by bjornregnell** [comment]
Fixed here: https://github.com/lunduniversity/introprog/commit/38aa0eb154a673e14aaba89be583f56089286a8e
