### ISSUE TITLE
Tools.md gives wrong advice on Legacy Boot

### ISSUE THREAD

**Issue by Annie-Wb** [lunduniversity/introprog#799]
In the WINDOWS section, it says that when running Dual Boot it is required to turn on legacy boot in BIOS, which is incorrect because 1. Modern Linux distros run on GPT instead of MBR, and 2. It can cause the computer to stop booting the original OS.

I'd like to have it removed.

**Comment by bjornregnell** [comment]
Sounds good! PR welcome! 

There is much to this (like turning of bitlocker etc etc) but I'd like to keep it as simple as possible and recommend beginners to talk to experienced dual booters... (Maybe the student guild (SRD) at LTH should have a nice page for dual booters, if not already.)

**Comment by Annie-Wb** [comment]
Added a [PR](https://github.com/lunduniversity/introprog/pull/800), for some reason it didn't auto-link with the issue.
