### ISSUE TITLE
The repl output from creating a range is different to what the compendium says.

### ISSUE THREAD

**Issue by lego-eden** [lunduniversity/introprog#804]
On page 67 in the compendium the output when creating a Range is as follows.
![20240909_18h35m28s_grim](https://github.com/user-attachments/assets/80210e14-cde4-42b0-873e-5f357ee00225)

The output in the latest repl version is different.
![20240909_18h43m01s_grim](https://github.com/user-attachments/assets/5dad7358-89d7-4ce0-89fe-2956ba8315a6)

The output in the compendium should be updated to match.

**Comment by bjornregnell** [comment]
Thanks. Fixed by: https://github.com/lunduniversity/introprog/commit/01596e5c1d16e0082e84aabfd1e12ba9e4b93067
