### ISSUE TITLE
Saknas ett bindesstreck på sidan 148 fråga f)

### ISSUE THREAD

**Issue by Nordre007** [lunduniversity/introprog#809]
Det står just nu "Kör kommandot scala-cli run . -main-class blockmole.run för att exekvera ditt
program och kontrollera utskriften i terminalfönstret." 
men det saknas ett bindesstreck framför main. Det borde vara:

scala-cli run . --main-class blockmole.run för att exekvera programmet

**Comment by bjornregnell** [comment]
good catch! we should also change `scala-cli` to `scala`
