### ISSUE TITLE
Compendium 5.1.14, Error instead of Warning

### ISSUE THREAD

**Issue by Annie-Wb** [lunduniversity/introprog#816]
According to 5.1.14, page 162, using an alphanumerical function should return a warning, but if using `-source:future` it returns an error.

When not using `-source:future` it returns a warning, meaning current version is the future that the compendium is referring to.

I propose changing the compendium to state that in Scala it's no longer allowed to use alphanumerical functions when not using dot notation. (`x.plus(y)` instead of `x plus y`)

![image](https://github.com/user-attachments/assets/21c17266-fb40-4880-99a2-4c696f7d233c)

**Comment by bjornregnell** [comment]
Yes - I did this yesterday... :)
https://github.com/lunduniversity/introprog/commit/c98ee0eba70d5d4a2051ccb2c94649a233d27276

**Comment by Annie-Wb** [comment]
Awesome, thank you!
Didn't see it as an issue but missed the commit.

**Comment by bjornregnell** [comment]
Well I could have opened an issue first and its not obvious which commits to check. But good to know that if I hadn't spotted this, someone else would :)
