### ISSUE TITLE
Wrongful implementation of a function in the course compendium (7.1.20 Implementation med generiska funktioner)

### ISSUE THREAD

**Issue by MaximilianUggla** [lunduniversity/introprog#846]
The implementation of def freq[T] throws not found error, because of usage of undeclared local varible x.
Current implementation:
`def freq[T](xs: Seq[T]): Seq[(T, Int)] =
    xs.distinct.map((_, xs.count(_ == x)))`

![image](https://github.com/user-attachments/assets/a71706cf-3d29-4e77-932c-90edc63ad77a)

Example solution:
`def freq[T](xs: Seq[T]): Seq[(T, Int)] =
    xs.distinct.map(x => x ->  xs.count(_ == x))`

**Comment by bjornregnell** [comment]
https://github.com/lunduniversity/introprog/commit/4f7dc74dfcb96f0be3342877bbc08ab0318440b0
