### ISSUE TITLE
Fel namn på metod i kompendiet

### ISSUE THREAD

**Issue by emmapaponja** [lunduniversity/introprog#850]
På sida 354, i del 10.1.40, ska det stå trait Sub extends Abstract**Def** { var x = 43 }, och inte trait Sub extends Abstract**Var** { var x = 43 } som det står för tillfället.
![Skärmbild 2024-11-20 141958](https://github.com/user-attachments/assets/b8679ab5-6846-44d9-b6f4-a9d387119401)

**Comment by bjornregnell** [comment]
After fix: 
![image](https://github.com/user-attachments/assets/1fe71d33-0932-44f4-8f7f-683e36f2ac38)
